/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiErrorResponseDto = { statusCode: number; message: string };

export const ApiErrorResponseDto$zodSchema: z.ZodType<ApiErrorResponseDto> = z
  .object({
    message: z.string().describe("Human-readable error message"),
    statusCode: z.number().describe("HTTP status code of the error"),
  });
