/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type AttachmentsControllerGetAttachmentDownloadUrlV1Request = {
  attachmentId: string;
};

export const AttachmentsControllerGetAttachmentDownloadUrlV1Request$zodSchema:
  z.ZodType<AttachmentsControllerGetAttachmentDownloadUrlV1Request> = z.object({
    attachmentId: z.string().describe("Unique attachment identifier"),
  });

/**
 * Download URL generated successfully
 */
export type AttachmentsControllerGetAttachmentDownloadUrlV1ResponseBody = {
  downloadUrl?: string | undefined;
  expiresIn?: number | undefined;
};

export const AttachmentsControllerGetAttachmentDownloadUrlV1ResponseBody$zodSchema:
  z.ZodType<AttachmentsControllerGetAttachmentDownloadUrlV1ResponseBody> = z
    .object({
      downloadUrl: z.string().optional().describe(
        "Signed URL for downloading the file",
      ),
      expiresIn: z.number().optional().describe(
        "URL expiration time in seconds",
      ),
    }).describe("Download URL generated successfully");

export type AttachmentsControllerGetAttachmentDownloadUrlV1Response =
  | ApiErrorResponseDto
  | AttachmentsControllerGetAttachmentDownloadUrlV1ResponseBody;

export const AttachmentsControllerGetAttachmentDownloadUrlV1Response$zodSchema:
  z.ZodType<AttachmentsControllerGetAttachmentDownloadUrlV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      AttachmentsControllerGetAttachmentDownloadUrlV1ResponseBody$zodSchema
    ),
  ]);
