/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  AttachmentResponseDto,
  AttachmentResponseDto$zodSchema,
} from "./attachmentresponsedto.js";

export type AttachmentsControllerCreateAttachmentV1Response =
  | AttachmentResponseDto
  | ApiErrorResponseDto;

export const AttachmentsControllerCreateAttachmentV1Response$zodSchema:
  z.ZodType<AttachmentsControllerCreateAttachmentV1Response> = z.union([
    AttachmentResponseDto$zodSchema,
    ApiErrorResponseDto$zodSchema,
  ]);
