/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export const AutomationsControllerGetTaskAutomationRunsV1Status = {
  Pending: "PENDING",
  Running: "RUNNING",
  Completed: "COMPLETED",
  Failed: "FAILED",
} as const;
export type AutomationsControllerGetTaskAutomationRunsV1Status = ClosedEnum<
  typeof AutomationsControllerGetTaskAutomationRunsV1Status
>;

export const AutomationsControllerGetTaskAutomationRunsV1Status$zodSchema = z
  .enum([
    "PENDING",
    "RUNNING",
    "COMPLETED",
    "FAILED",
  ]);

export const Trigger = {
  Manual: "MANUAL",
  Scheduled: "SCHEDULED",
  Event: "EVENT",
} as const;
export type Trigger = ClosedEnum<typeof Trigger>;

export const Trigger$zodSchema = z.enum([
  "MANUAL",
  "SCHEDULED",
  "EVENT",
]);

export type AutomationsControllerGetTaskAutomationRunsV1Request = {
  taskId: string;
};

export const AutomationsControllerGetTaskAutomationRunsV1Request$zodSchema:
  z.ZodType<AutomationsControllerGetTaskAutomationRunsV1Request> = z.object({
    taskId: z.string().describe("Task ID"),
  });

export type AutomationsControllerGetTaskAutomationRunsV1Error = {};

export const AutomationsControllerGetTaskAutomationRunsV1Error$zodSchema:
  z.ZodType<AutomationsControllerGetTaskAutomationRunsV1Error> = z.object({});

export type ResponseBody = {
  id?: string | undefined;
  status?: AutomationsControllerGetTaskAutomationRunsV1Status | undefined;
  trigger?: Trigger | undefined;
  createdAt?: string | undefined;
  completedAt?: string | null | undefined;
  error?: AutomationsControllerGetTaskAutomationRunsV1Error | null | undefined;
};

export const ResponseBody$zodSchema: z.ZodType<ResponseBody> = z.object({
  completedAt: z.iso.datetime({ offset: true }).nullable().optional(),
  createdAt: z.iso.datetime({ offset: true }).optional(),
  error: z.lazy(() =>
    AutomationsControllerGetTaskAutomationRunsV1Error$zodSchema
  ).nullable().optional(),
  id: z.string().optional(),
  status: AutomationsControllerGetTaskAutomationRunsV1Status$zodSchema
    .optional(),
  trigger: Trigger$zodSchema.optional(),
});

export type AutomationsControllerGetTaskAutomationRunsV1Response =
  | ApiErrorResponseDto
  | Array<ResponseBody>;

export const AutomationsControllerGetTaskAutomationRunsV1Response$zodSchema:
  z.ZodType<AutomationsControllerGetTaskAutomationRunsV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.array(z.lazy(() => ResponseBody$zodSchema)).describe(
      "Automation runs retrieved successfully",
    ),
  ]);
