/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type AutomationsControllerGetAutomationVersionsV1Request = {
  taskId: string;
  automationId: string;
  limit: string;
  offset: string;
};

export const AutomationsControllerGetAutomationVersionsV1Request$zodSchema:
  z.ZodType<AutomationsControllerGetAutomationVersionsV1Request> = z.object({
    automationId: z.string().describe("Automation ID"),
    limit: z.string(),
    offset: z.string(),
    taskId: z.string().describe("Task ID"),
  });

export type AutomationsControllerGetAutomationVersionsV1Version = {
  id?: string | undefined;
  version?: number | undefined;
  scriptKey?: string | undefined;
  changelog?: string | null | undefined;
  publishedBy?: string | null | undefined;
  createdAt?: string | undefined;
};

export const AutomationsControllerGetAutomationVersionsV1Version$zodSchema:
  z.ZodType<AutomationsControllerGetAutomationVersionsV1Version> = z.object({
    changelog: z.string().nullable().optional(),
    createdAt: z.iso.datetime({ offset: true }).optional(),
    id: z.string().optional(),
    publishedBy: z.string().nullable().optional(),
    scriptKey: z.string().optional(),
    version: z.number().optional(),
  });

/**
 * Versions retrieved successfully
 */
export type AutomationsControllerGetAutomationVersionsV1ResponseBody = {
  success?: boolean | undefined;
  versions?:
    | Array<AutomationsControllerGetAutomationVersionsV1Version>
    | undefined;
};

export const AutomationsControllerGetAutomationVersionsV1ResponseBody$zodSchema:
  z.ZodType<AutomationsControllerGetAutomationVersionsV1ResponseBody> = z
    .object({
      success: z.boolean().optional(),
      versions: z.array(
        z.lazy(() =>
          AutomationsControllerGetAutomationVersionsV1Version$zodSchema
        ),
      ).optional(),
    }).describe("Versions retrieved successfully");

export type AutomationsControllerGetAutomationVersionsV1Response =
  | ApiErrorResponseDto
  | AutomationsControllerGetAutomationVersionsV1ResponseBody;

export const AutomationsControllerGetAutomationVersionsV1Response$zodSchema:
  z.ZodType<AutomationsControllerGetAutomationVersionsV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      AutomationsControllerGetAutomationVersionsV1ResponseBody$zodSchema
    ),
  ]);
