/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type AutomationsControllerCreateAutomationV1Request = { taskId: string };

export const AutomationsControllerCreateAutomationV1Request$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1Request> = z.object({
    taskId: z.string().describe("Unique task identifier"),
  });

export type AutomationsControllerCreateAutomationV1Automation = {
  id?: string | undefined;
  name?: string | undefined;
};

export const AutomationsControllerCreateAutomationV1Automation$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1Automation> = z.object({
    id: z.string().optional(),
    name: z.string().optional(),
  });

/**
 * Automation created successfully
 */
export type AutomationsControllerCreateAutomationV1ResponseBody = {
  success?: boolean | undefined;
  automation?: AutomationsControllerCreateAutomationV1Automation | undefined;
};

export const AutomationsControllerCreateAutomationV1ResponseBody$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1ResponseBody> = z.object({
    automation: z.lazy(() =>
      AutomationsControllerCreateAutomationV1Automation$zodSchema
    ).optional(),
    success: z.boolean().optional(),
  }).describe("Automation created successfully");

export type AutomationsControllerCreateAutomationV1Response =
  | ApiErrorResponseDto
  | AutomationsControllerCreateAutomationV1ResponseBody;

export const AutomationsControllerCreateAutomationV1Response$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() => AutomationsControllerCreateAutomationV1ResponseBody$zodSchema),
  ]);
