/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  UpdateAutomationDto,
  UpdateAutomationDto$zodSchema,
} from "./updateautomationdto.js";

export type AutomationsControllerUpdateAutomationV1Request = {
  taskId: string;
  automationId: string;
  body: UpdateAutomationDto;
};

export const AutomationsControllerUpdateAutomationV1Request$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1Request> = z.object({
    automationId: z.string().describe("Unique automation identifier"),
    body: UpdateAutomationDto$zodSchema,
    taskId: z.string().describe("Unique task identifier"),
  });

export type AutomationsControllerUpdateAutomationV1Automation = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
};

export const AutomationsControllerUpdateAutomationV1Automation$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1Automation> = z.object({
    description: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
  });

/**
 * Automation updated successfully
 */
export type AutomationsControllerUpdateAutomationV1ResponseBody = {
  success?: boolean | undefined;
  automation?: AutomationsControllerUpdateAutomationV1Automation | undefined;
};

export const AutomationsControllerUpdateAutomationV1ResponseBody$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1ResponseBody> = z.object({
    automation: z.lazy(() =>
      AutomationsControllerUpdateAutomationV1Automation$zodSchema
    ).optional(),
    success: z.boolean().optional(),
  }).describe("Automation updated successfully");

export type AutomationsControllerUpdateAutomationV1Response =
  | ApiErrorResponseDto
  | AutomationsControllerUpdateAutomationV1ResponseBody;

export const AutomationsControllerUpdateAutomationV1Response$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() => AutomationsControllerUpdateAutomationV1ResponseBody$zodSchema),
  ]);
