/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

/**
 * Delete comment request body
 */
export type CommentsControllerDeleteCommentV1RequestBody = {
  userId?: string | undefined;
};

export const CommentsControllerDeleteCommentV1RequestBody$zodSchema: z.ZodType<
  CommentsControllerDeleteCommentV1RequestBody
> = z.object({
  userId: z.string().optional().describe(
    "User ID of the comment author (required for API key auth, ignored for JWT auth)",
  ),
}).describe("Delete comment request body");

export type CommentsControllerDeleteCommentV1Request = {
  commentId: string;
  body: CommentsControllerDeleteCommentV1RequestBody;
};

export const CommentsControllerDeleteCommentV1Request$zodSchema: z.ZodType<
  CommentsControllerDeleteCommentV1Request
> = z.object({
  body: z.lazy(() => CommentsControllerDeleteCommentV1RequestBody$zodSchema)
    .describe("Delete comment request body"),
  commentId: z.string().describe("Unique comment identifier"),
});

/**
 * Comment deleted successfully
 */
export type CommentsControllerDeleteCommentV1ResponseBody = {
  success?: boolean | undefined;
  deletedCommentId?: string | undefined;
  message?: string | undefined;
};

export const CommentsControllerDeleteCommentV1ResponseBody$zodSchema: z.ZodType<
  CommentsControllerDeleteCommentV1ResponseBody
> = z.object({
  deletedCommentId: z.string().optional(),
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Comment deleted successfully");

export type CommentsControllerDeleteCommentV1Response =
  | ApiErrorResponseDto
  | CommentsControllerDeleteCommentV1ResponseBody;

export const CommentsControllerDeleteCommentV1Response$zodSchema: z.ZodType<
  CommentsControllerDeleteCommentV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => CommentsControllerDeleteCommentV1ResponseBody$zodSchema),
]);
