/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  CommentResponseDto,
  CommentResponseDto$zodSchema,
} from "./commentresponsedto.js";

export type CommentsControllerCreateCommentV1Response =
  | CommentResponseDto
  | ApiErrorResponseDto;

export const CommentsControllerCreateCommentV1Response$zodSchema: z.ZodType<
  CommentsControllerCreateCommentV1Response
> = z.union([
  CommentResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
