/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export const ContextControllerGetContextByIdV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
export type ContextControllerGetContextByIdV1AuthType = ClosedEnum<
  typeof ContextControllerGetContextByIdV1AuthType
>;

export const ContextControllerGetContextByIdV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]);

export type ContextControllerGetContextByIdV1Request = { id: string };

export const ContextControllerGetContextByIdV1Request$zodSchema: z.ZodType<
  ContextControllerGetContextByIdV1Request
> = z.object({
  id: z.string().describe("Context entry ID"),
});

/**
 * Context entry retrieved successfully
 */
export type ContextControllerGetContextByIdV1ResponseBody = {
  id?: string | undefined;
  organizationId?: string | undefined;
  question?: string | undefined;
  answer?: string | undefined;
  tags?: Array<string> | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  authType?: ContextControllerGetContextByIdV1AuthType | undefined;
};

export const ContextControllerGetContextByIdV1ResponseBody$zodSchema: z.ZodType<
  ContextControllerGetContextByIdV1ResponseBody
> = z.object({
  answer: z.string().optional(),
  authType: ContextControllerGetContextByIdV1AuthType$zodSchema.optional(),
  createdAt: z.iso.datetime({ offset: true }).optional(),
  id: z.string().optional(),
  organizationId: z.string().optional(),
  question: z.string().optional(),
  tags: z.array(z.string()).optional(),
  updatedAt: z.iso.datetime({ offset: true }).optional(),
}).describe("Context entry retrieved successfully");

export type ContextControllerGetContextByIdV1Response =
  | ApiErrorResponseDto
  | ContextControllerGetContextByIdV1ResponseBody;

export const ContextControllerGetContextByIdV1Response$zodSchema: z.ZodType<
  ContextControllerGetContextByIdV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => ContextControllerGetContextByIdV1ResponseBody$zodSchema),
]);
