/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ControlsControllerDeleteV1Request = { id: string };

export const ControlsControllerDeleteV1Request$zodSchema: z.ZodType<
  ControlsControllerDeleteV1Request
> = z.object({
  id: z.string(),
});
