/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export const ContextControllerDeleteContextV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
export type ContextControllerDeleteContextV1AuthType = ClosedEnum<
  typeof ContextControllerDeleteContextV1AuthType
>;

export const ContextControllerDeleteContextV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]);

export type ContextControllerDeleteContextV1Request = { id: string };

export const ContextControllerDeleteContextV1Request$zodSchema: z.ZodType<
  ContextControllerDeleteContextV1Request
> = z.object({
  id: z.string().describe("Context entry ID"),
});

export type DeletedContext = {
  id?: string | undefined;
  question?: string | undefined;
};

export const DeletedContext$zodSchema: z.ZodType<DeletedContext> = z.object({
  id: z.string().optional(),
  question: z.string().optional(),
});

/**
 * Context entry deleted successfully
 */
export type ContextControllerDeleteContextV1ResponseBody = {
  message?: string | undefined;
  deletedContext?: DeletedContext | undefined;
  authType?: ContextControllerDeleteContextV1AuthType | undefined;
};

export const ContextControllerDeleteContextV1ResponseBody$zodSchema: z.ZodType<
  ContextControllerDeleteContextV1ResponseBody
> = z.object({
  authType: ContextControllerDeleteContextV1AuthType$zodSchema.optional(),
  deletedContext: z.lazy(() => DeletedContext$zodSchema).optional(),
  message: z.string().optional(),
}).describe("Context entry deleted successfully");

export type ContextControllerDeleteContextV1Response =
  | ApiErrorResponseDto
  | ContextControllerDeleteContextV1ResponseBody;

export const ContextControllerDeleteContextV1Response$zodSchema: z.ZodType<
  ContextControllerDeleteContextV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => ContextControllerDeleteContextV1ResponseBody$zodSchema),
]);
