/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export const ContextControllerCreateContextV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
export type ContextControllerCreateContextV1AuthType = ClosedEnum<
  typeof ContextControllerCreateContextV1AuthType
>;

export const ContextControllerCreateContextV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]);

/**
 * Bad request - Invalid input data
 */
export type ContextControllerCreateContextV1BadRequestResponseBody = {
  message?: Array<string> | undefined;
  error?: string | undefined;
  statusCode?: number | undefined;
};

export const ContextControllerCreateContextV1BadRequestResponseBody$zodSchema:
  z.ZodType<ContextControllerCreateContextV1BadRequestResponseBody> = z.object({
    error: z.string().optional(),
    message: z.array(z.string()).optional(),
    statusCode: z.number().optional(),
  }).describe("Bad request - Invalid input data");

/**
 * Context entry created successfully
 */
export type ContextControllerCreateContextV1ResponseBody = {
  id?: string | undefined;
  organizationId?: string | undefined;
  question?: string | undefined;
  answer?: string | undefined;
  tags?: Array<string> | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  authType?: ContextControllerCreateContextV1AuthType | undefined;
};

export const ContextControllerCreateContextV1ResponseBody$zodSchema: z.ZodType<
  ContextControllerCreateContextV1ResponseBody
> = z.object({
  answer: z.string().optional(),
  authType: ContextControllerCreateContextV1AuthType$zodSchema.optional(),
  createdAt: z.iso.datetime({ offset: true }).optional(),
  id: z.string().optional(),
  organizationId: z.string().optional(),
  question: z.string().optional(),
  tags: z.array(z.string()).optional(),
  updatedAt: z.iso.datetime({ offset: true }).optional(),
}).describe("Context entry created successfully");

export type ContextControllerCreateContextV1Response =
  | ApiErrorResponseDto
  | ContextControllerCreateContextV1ResponseBody
  | ContextControllerCreateContextV1BadRequestResponseBody;

export const ContextControllerCreateContextV1Response$zodSchema: z.ZodType<
  ContextControllerCreateContextV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => ContextControllerCreateContextV1ResponseBody$zodSchema),
  z.lazy(() =>
    ContextControllerCreateContextV1BadRequestResponseBody$zodSchema
  ),
]);
