/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { LinkTasksDto, LinkTasksDto$zodSchema } from "./linktasksdto.js";

export type ControlsControllerLinkTasksV1Request = {
  id: string;
  frameworkInstanceId: string;
  body: LinkTasksDto;
};

export const ControlsControllerLinkTasksV1Request$zodSchema: z.ZodType<
  ControlsControllerLinkTasksV1Request
> = z.object({
  body: LinkTasksDto$zodSchema,
  frameworkInstanceId: z.string(),
  id: z.string(),
});
