/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateConnectionDto = {
  organizationId?: string | undefined;
  providerSlug: string;
  credentials?: { [k: string]: any } | undefined;
};

export const CreateConnectionDto$zodSchema: z.ZodType<CreateConnectionDto> = z
  .object({
    credentials: z.record(z.string(), z.any()).optional().describe(
      "Provider-specific credential fields. Keys differ by provider — call get-provider-details for the exact shape. For AWS (Cloud Tests) the fields are: connectionName (display name), awsType ('aws-commercial' or 'aws-govcloud'), roleArn (auditor role), regions (string array), remediationRoles (JSON string map of '<AssetClass>:<region>' to remediation role ARN, e.g. '{\"Storage:us-east-1\":\"arn:aws:iam::123456789012:role/OpenComp-Remediator-Storage-us-east-1\"}' — one role per pair; the legacy single remediationRoleArn is rejected for new connections and only still read on existing ones), and awsScanMode ('comp_scanners' or 'security_hub'). The externalId is always minted server-side (org_<orgId>_<uuid>) — any client-supplied value is ignored. Omit roleArn to create a pending connection: the response returns the minted externalId show-once for the CloudShell setup script, then PUT credentials with the Role ARN to validate and activate. Omit credentials for OAuth providers — use POST /v1/integrations/oauth/start instead.",
    ),
    organizationId: z.string().optional().describe(
      "Auto-resolved from your API key / session. You can omit this; it is ignored by the server.",
    ),
    providerSlug: z.string().describe(
      "Provider slug for the integration. Call list-providers first to see the available slugs (e.g. 'aws', 'gcp', 'azure', 'github').",
    ),
  });
