/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateRiskAcceptanceDto = {
  acceptedById?: string | undefined;
  notes?: string | undefined;
};

export const CreateRiskAcceptanceDto$zodSchema: z.ZodType<
  CreateRiskAcceptanceDto
> = z.object({
  acceptedById: z.string().optional().describe(
    "Member ID of the acceptor. Defaults to the risk owner (assignee) when omitted.",
  ),
  notes: z.string().optional().describe(
    "Optional notes recorded with the acceptance.",
  ),
});
