/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  DeviceResponseDto,
  DeviceResponseDto$zodSchema,
} from "./deviceresponsedto.js";

/**
 * How the request was authenticated
 */
export const DevicesControllerGetAllDevicesV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type DevicesControllerGetAllDevicesV1AuthType = ClosedEnum<
  typeof DevicesControllerGetAllDevicesV1AuthType
>;

export const DevicesControllerGetAllDevicesV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]).describe("How the request was authenticated");

export type DevicesControllerGetAllDevicesV1AuthenticatedUser = {
  id?: string | undefined;
  email?: string | undefined;
};

export const DevicesControllerGetAllDevicesV1AuthenticatedUser$zodSchema:
  z.ZodType<DevicesControllerGetAllDevicesV1AuthenticatedUser> = z.object({
    email: z.string().optional().describe("User email"),
    id: z.string().optional().describe("User ID"),
  });

/**
 * Devices retrieved successfully
 */
export type DevicesControllerGetAllDevicesV1ResponseBody = {
  data?: Array<DeviceResponseDto> | undefined;
  count?: number | undefined;
  authType?: DevicesControllerGetAllDevicesV1AuthType | undefined;
  authenticatedUser?:
    | DevicesControllerGetAllDevicesV1AuthenticatedUser
    | undefined;
};

export const DevicesControllerGetAllDevicesV1ResponseBody$zodSchema: z.ZodType<
  DevicesControllerGetAllDevicesV1ResponseBody
> = z.object({
  authType: DevicesControllerGetAllDevicesV1AuthType$zodSchema.optional()
    .describe("How the request was authenticated"),
  authenticatedUser: z.lazy(() =>
    DevicesControllerGetAllDevicesV1AuthenticatedUser$zodSchema
  ).optional(),
  count: z.number().optional().describe("Total number of devices"),
  data: z.array(DeviceResponseDto$zodSchema).optional(),
}).describe("Devices retrieved successfully");

export type DevicesControllerGetAllDevicesV1Response =
  | ApiErrorResponseDto
  | DevicesControllerGetAllDevicesV1ResponseBody;

export const DevicesControllerGetAllDevicesV1Response$zodSchema: z.ZodType<
  DevicesControllerGetAllDevicesV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => DevicesControllerGetAllDevicesV1ResponseBody$zodSchema),
]);
