/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  DevicesByMemberResponseDto,
  DevicesByMemberResponseDto$zodSchema,
} from "./devicesbymemberresponsedto.js";

export type DevicesControllerGetDevicesByMemberV1Request = { memberId: string };

export const DevicesControllerGetDevicesByMemberV1Request$zodSchema: z.ZodType<
  DevicesControllerGetDevicesByMemberV1Request
> = z.object({
  memberId: z.string().describe("Member ID to get devices for"),
});

export type DevicesControllerGetDevicesByMemberV1Response =
  | DevicesByMemberResponseDto
  | ApiErrorResponseDto;

export const DevicesControllerGetDevicesByMemberV1Response$zodSchema: z.ZodType<
  DevicesControllerGetDevicesByMemberV1Response
> = z.union([
  DevicesByMemberResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
