/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FrameworksControllerGetSyncHistoryV1Request = { id: string };

export const FrameworksControllerGetSyncHistoryV1Request$zodSchema: z.ZodType<
  FrameworksControllerGetSyncHistoryV1Request
> = z.object({
  id: z.string(),
});
