/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FrameworksControllerFindAllV1Request = {
  includeControls?: boolean | undefined;
  includeScores?: boolean | undefined;
};

export const FrameworksControllerFindAllV1Request$zodSchema: z.ZodType<
  FrameworksControllerFindAllV1Request
> = z.object({
  includeControls: z.boolean().optional(),
  includeScores: z.boolean().optional(),
});
