/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FrameworksControllerFindOneV1Request = { id: string };

export const FrameworksControllerFindOneV1Request$zodSchema: z.ZodType<
  FrameworksControllerFindOneV1Request
> = z.object({
  id: z.string(),
});
