/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FrameworksControllerFindRequirementV1Request = {
  id: string;
  requirementKey: string;
};

export const FrameworksControllerFindRequirementV1Request$zodSchema: z.ZodType<
  FrameworksControllerFindRequirementV1Request
> = z.object({
  id: z.string(),
  requirementKey: z.string(),
});
