/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  RollbackFrameworkDto,
  RollbackFrameworkDto$zodSchema,
} from "./rollbackframeworkdto.js";

export type FrameworksControllerRollbackFrameworkV1Request = {
  id: string;
  body: RollbackFrameworkDto;
};

export const FrameworksControllerRollbackFrameworkV1Request$zodSchema:
  z.ZodType<FrameworksControllerRollbackFrameworkV1Request> = z.object({
    body: RollbackFrameworkDto$zodSchema,
    id: z.string(),
  });
