/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FrameworksControllerDeleteV1Request = { id: string };

export const FrameworksControllerDeleteV1Request$zodSchema: z.ZodType<
  FrameworksControllerDeleteV1Request
> = z.object({
  id: z.string(),
});
