/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FrameworksControllerGetUpdatePreviewV1Request = { id: string };

export const FrameworksControllerGetUpdatePreviewV1Request$zodSchema: z.ZodType<
  FrameworksControllerGetUpdatePreviewV1Request
> = z.object({
  id: z.string(),
});
