/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateCustomRequirementDto,
  CreateCustomRequirementDto$zodSchema,
} from "./createcustomrequirementdto.js";

export type FrameworksControllerCreateRequirementV1Request = {
  id: string;
  body: CreateCustomRequirementDto;
};

export const FrameworksControllerCreateRequirementV1Request$zodSchema:
  z.ZodType<FrameworksControllerCreateRequirementV1Request> = z.object({
    body: CreateCustomRequirementDto$zodSchema,
    id: z.string(),
  });
