/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  LinkRequirementsDto,
  LinkRequirementsDto$zodSchema,
} from "./linkrequirementsdto.js";

export type FrameworksControllerLinkRequirementsV1Request = {
  id: string;
  body: LinkRequirementsDto;
};

export const FrameworksControllerLinkRequirementsV1Request$zodSchema: z.ZodType<
  FrameworksControllerLinkRequirementsV1Request
> = z.object({
  body: LinkRequirementsDto$zodSchema,
  id: z.string(),
});
