/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IsmsControllerRiskTreatmentV1Request = { id: string };

export const IsmsControllerRiskTreatmentV1Request$zodSchema: z.ZodType<
  IsmsControllerRiskTreatmentV1Request
> = z.object({
  id: z.string(),
});
