/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

/**
 * How the request was authenticated
 */
export const OrganizationControllerDeleteOrganizationV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type OrganizationControllerDeleteOrganizationV1AuthType = ClosedEnum<
  typeof OrganizationControllerDeleteOrganizationV1AuthType
>;

export const OrganizationControllerDeleteOrganizationV1AuthType$zodSchema = z
  .enum([
    "api-key",
    "session",
  ]).describe("How the request was authenticated");

export type DeletedOrganization = {
  id?: string | undefined;
  name?: string | undefined;
};

export const DeletedOrganization$zodSchema: z.ZodType<DeletedOrganization> = z
  .object({
    id: z.string().optional().describe("The deleted organization ID"),
    name: z.string().optional().describe("The deleted organization name"),
  });

/**
 * Organization deleted successfully
 */
export type OrganizationControllerDeleteOrganizationV1ResponseBody = {
  success?: boolean | undefined;
  deletedOrganization?: DeletedOrganization | undefined;
  authType?: OrganizationControllerDeleteOrganizationV1AuthType | undefined;
};

export const OrganizationControllerDeleteOrganizationV1ResponseBody$zodSchema:
  z.ZodType<OrganizationControllerDeleteOrganizationV1ResponseBody> = z.object({
    authType: OrganizationControllerDeleteOrganizationV1AuthType$zodSchema
      .optional().describe("How the request was authenticated"),
    deletedOrganization: z.lazy(() => DeletedOrganization$zodSchema).optional(),
    success: z.boolean().optional().describe("Indicates successful deletion"),
  }).describe("Organization deleted successfully");

export type OrganizationControllerDeleteOrganizationV1Response =
  | ApiErrorResponseDto
  | OrganizationControllerDeleteOrganizationV1ResponseBody;

export const OrganizationControllerDeleteOrganizationV1Response$zodSchema:
  z.ZodType<OrganizationControllerDeleteOrganizationV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      OrganizationControllerDeleteOrganizationV1ResponseBody$zodSchema
    ),
  ]);
