/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  PeopleResponseDto,
  PeopleResponseDto$zodSchema,
} from "./peopleresponsedto.js";
import {
  UpdatePeopleDto,
  UpdatePeopleDto$zodSchema,
} from "./updatepeopledto.js";

export type PeopleControllerUpdateMemberV1Request = {
  id: string;
  body: UpdatePeopleDto;
};

export const PeopleControllerUpdateMemberV1Request$zodSchema: z.ZodType<
  PeopleControllerUpdateMemberV1Request
> = z.object({
  body: UpdatePeopleDto$zodSchema.describe("Member update data"),
  id: z.string().describe("Member ID"),
});

export type PeopleControllerUpdateMemberV1Response =
  | PeopleResponseDto
  | ApiErrorResponseDto;

export const PeopleControllerUpdateMemberV1Response$zodSchema: z.ZodType<
  PeopleControllerUpdateMemberV1Response
> = z.union([
  PeopleResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
