/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  PeopleResponseDto,
  PeopleResponseDto$zodSchema,
} from "./peopleresponsedto.js";

export type PeopleControllerUnlinkDeviceV1Request = { id: string };

export const PeopleControllerUnlinkDeviceV1Request$zodSchema: z.ZodType<
  PeopleControllerUnlinkDeviceV1Request
> = z.object({
  id: z.string().describe("Member ID"),
});

export type PeopleControllerUnlinkDeviceV1Response =
  | PeopleResponseDto
  | ApiErrorResponseDto;

export const PeopleControllerUnlinkDeviceV1Response$zodSchema: z.ZodType<
  PeopleControllerUnlinkDeviceV1Response
> = z.union([
  PeopleResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
