/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  PeopleResponseDto,
  PeopleResponseDto$zodSchema,
} from "./peopleresponsedto.js";

/**
 * How the request was authenticated
 */
export const PeopleControllerBulkCreateMembersV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type PeopleControllerBulkCreateMembersV1AuthType = ClosedEnum<
  typeof PeopleControllerBulkCreateMembersV1AuthType
>;

export const PeopleControllerBulkCreateMembersV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]).describe("How the request was authenticated");

export type PeopleControllerBulkCreateMembersV1Error = {
  index?: number | undefined;
  userId?: string | undefined;
  error?: string | undefined;
};

export const PeopleControllerBulkCreateMembersV1Error$zodSchema: z.ZodType<
  PeopleControllerBulkCreateMembersV1Error
> = z.object({
  error: z.string().optional().describe(
    "Error message explaining why the member could not be created",
  ),
  index: z.number().optional().describe(
    "Index in the original array where the error occurred",
  ),
  userId: z.string().optional().describe("User ID that failed to be added"),
});

export type Summary = {
  total?: number | undefined;
  successful?: number | undefined;
  failed?: number | undefined;
};

export const Summary$zodSchema: z.ZodType<Summary> = z.object({
  failed: z.number().optional().describe(
    "Number of members that failed to be created",
  ),
  successful: z.number().optional().describe(
    "Number of members successfully created",
  ),
  total: z.number().optional().describe(
    "Total number of members in the request",
  ),
});

export type PeopleControllerBulkCreateMembersV1AuthenticatedUser = {
  id?: string | undefined;
  email?: string | undefined;
};

export const PeopleControllerBulkCreateMembersV1AuthenticatedUser$zodSchema:
  z.ZodType<PeopleControllerBulkCreateMembersV1AuthenticatedUser> = z.object({
    email: z.string().optional().describe("User email"),
    id: z.string().optional().describe("User ID"),
  });

/**
 * Bulk member creation completed
 */
export type PeopleControllerBulkCreateMembersV1ResponseBody = {
  created?: Array<PeopleResponseDto> | undefined;
  errors?: Array<PeopleControllerBulkCreateMembersV1Error> | undefined;
  summary?: Summary | undefined;
  authType?: PeopleControllerBulkCreateMembersV1AuthType | undefined;
  authenticatedUser?:
    | PeopleControllerBulkCreateMembersV1AuthenticatedUser
    | undefined;
};

export const PeopleControllerBulkCreateMembersV1ResponseBody$zodSchema:
  z.ZodType<PeopleControllerBulkCreateMembersV1ResponseBody> = z.object({
    authType: PeopleControllerBulkCreateMembersV1AuthType$zodSchema.optional()
      .describe("How the request was authenticated"),
    authenticatedUser: z.lazy(() =>
      PeopleControllerBulkCreateMembersV1AuthenticatedUser$zodSchema
    ).optional(),
    created: z.array(PeopleResponseDto$zodSchema).optional().describe(
      "Successfully created members",
    ),
    errors: z.array(
      z.lazy(() => PeopleControllerBulkCreateMembersV1Error$zodSchema),
    ).optional().describe(
      "Members that failed to be created with error details",
    ),
    summary: z.lazy(() => Summary$zodSchema).optional(),
  }).describe("Bulk member creation completed");

export type PeopleControllerBulkCreateMembersV1Response =
  | ApiErrorResponseDto
  | PeopleControllerBulkCreateMembersV1ResponseBody;

export const PeopleControllerBulkCreateMembersV1Response$zodSchema: z.ZodType<
  PeopleControllerBulkCreateMembersV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => PeopleControllerBulkCreateMembersV1ResponseBody$zodSchema),
]);
