/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  PeopleResponseDto,
  PeopleResponseDto$zodSchema,
} from "./peopleresponsedto.js";

export type PeopleControllerCreateMemberV1Response =
  | PeopleResponseDto
  | ApiErrorResponseDto;

export const PeopleControllerCreateMemberV1Response$zodSchema: z.ZodType<
  PeopleControllerCreateMemberV1Response
> = z.union([
  PeopleResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
