/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

/**
 * How the request was authenticated
 */
export const PeopleControllerRemoveHostV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type PeopleControllerRemoveHostV1AuthType = ClosedEnum<
  typeof PeopleControllerRemoveHostV1AuthType
>;

export const PeopleControllerRemoveHostV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]).describe("How the request was authenticated");

export type PeopleControllerRemoveHostV1Request = {
  id: string;
  hostId: number;
};

export const PeopleControllerRemoveHostV1Request$zodSchema: z.ZodType<
  PeopleControllerRemoveHostV1Request
> = z.object({
  hostId: z.number().describe("FleetDM host ID"),
  id: z.string().describe("Member ID"),
});

/**
 * Host removed from Fleet successfully
 */
export type PeopleControllerRemoveHostV1ResponseBody = {
  success?: boolean | undefined;
  authType?: PeopleControllerRemoveHostV1AuthType | undefined;
};

export const PeopleControllerRemoveHostV1ResponseBody$zodSchema: z.ZodType<
  PeopleControllerRemoveHostV1ResponseBody
> = z.object({
  authType: PeopleControllerRemoveHostV1AuthType$zodSchema.optional().describe(
    "How the request was authenticated",
  ),
  success: z.boolean().optional().describe("Indicates successful removal"),
}).describe("Host removed from Fleet successfully");

export type PeopleControllerRemoveHostV1Response =
  | ApiErrorResponseDto
  | PeopleControllerRemoveHostV1ResponseBody;

export const PeopleControllerRemoveHostV1Response$zodSchema: z.ZodType<
  PeopleControllerRemoveHostV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => PeopleControllerRemoveHostV1ResponseBody$zodSchema),
]);
