/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

/**
 * How the request was authenticated
 */
export const PeopleControllerDeleteMemberV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type PeopleControllerDeleteMemberV1AuthType = ClosedEnum<
  typeof PeopleControllerDeleteMemberV1AuthType
>;

export const PeopleControllerDeleteMemberV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]).describe("How the request was authenticated");

export type PeopleControllerDeleteMemberV1Request = {
  id: string;
  skipOffboarding: string;
};

export const PeopleControllerDeleteMemberV1Request$zodSchema: z.ZodType<
  PeopleControllerDeleteMemberV1Request
> = z.object({
  id: z.string().describe("Member ID"),
  skipOffboarding: z.string(),
});

export type DeletedMember = {
  id?: string | undefined;
  name?: string | undefined;
  email?: string | undefined;
};

export const DeletedMember$zodSchema: z.ZodType<DeletedMember> = z.object({
  email: z.string().optional().describe("The deleted member email"),
  id: z.string().optional().describe("The deleted member ID"),
  name: z.string().optional().describe("The deleted member name"),
});

/**
 * Member deleted successfully
 */
export type PeopleControllerDeleteMemberV1ResponseBody = {
  success?: boolean | undefined;
  deletedMember?: DeletedMember | undefined;
  authType?: PeopleControllerDeleteMemberV1AuthType | undefined;
};

export const PeopleControllerDeleteMemberV1ResponseBody$zodSchema: z.ZodType<
  PeopleControllerDeleteMemberV1ResponseBody
> = z.object({
  authType: PeopleControllerDeleteMemberV1AuthType$zodSchema.optional()
    .describe("How the request was authenticated"),
  deletedMember: z.lazy(() => DeletedMember$zodSchema).optional(),
  success: z.boolean().optional().describe("Indicates successful deletion"),
}).describe("Member deleted successfully");

export type PeopleControllerDeleteMemberV1Response =
  | ApiErrorResponseDto
  | PeopleControllerDeleteMemberV1ResponseBody;

export const PeopleControllerDeleteMemberV1Response$zodSchema: z.ZodType<
  PeopleControllerDeleteMemberV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => PeopleControllerDeleteMemberV1ResponseBody$zodSchema),
]);
