/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  CreatePolicyDto,
  CreatePolicyDto$zodSchema,
} from "./createpolicydto.js";
import {
  PolicyResponseDto,
  PolicyResponseDto$zodSchema,
} from "./policyresponsedto.js";

export type PoliciesControllerCreatePolicyV1Request = {
  xOrganizationId?: string | undefined;
  body: CreatePolicyDto;
};

export const PoliciesControllerCreatePolicyV1Request$zodSchema: z.ZodType<
  PoliciesControllerCreatePolicyV1Request
> = z.object({
  body: CreatePolicyDto$zodSchema.describe("Policy creation data"),
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});

export type PoliciesControllerCreatePolicyV1Response =
  | PolicyResponseDto
  | ApiErrorResponseDto;

export const PoliciesControllerCreatePolicyV1Response$zodSchema: z.ZodType<
  PoliciesControllerCreatePolicyV1Response
> = z.union([
  PolicyResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
