/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  PolicyPdfUploadUrlResponseDto,
  PolicyPdfUploadUrlResponseDto$zodSchema,
} from "./policypdfuploadurlresponsedto.js";
import {
  RequestPolicyPdfUploadUrlDto,
  RequestPolicyPdfUploadUrlDto$zodSchema,
} from "./requestpolicypdfuploadurldto.js";

export type PoliciesControllerRequestPolicyPdfUploadUrlV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  body: RequestPolicyPdfUploadUrlDto;
};

export const PoliciesControllerRequestPolicyPdfUploadUrlV1Request$zodSchema:
  z.ZodType<PoliciesControllerRequestPolicyPdfUploadUrlV1Request> = z.object({
    body: RequestPolicyPdfUploadUrlDto$zodSchema,
    id: z.string().describe("Policy ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

export type PoliciesControllerRequestPolicyPdfUploadUrlV1Response =
  | PolicyPdfUploadUrlResponseDto
  | ApiErrorResponseDto;

export const PoliciesControllerRequestPolicyPdfUploadUrlV1Response$zodSchema:
  z.ZodType<PoliciesControllerRequestPolicyPdfUploadUrlV1Response> = z.union([
    PolicyPdfUploadUrlResponseDto$zodSchema,
    ApiErrorResponseDto$zodSchema,
  ]);
