/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

/**
 * How the request was authenticated
 */
export const PoliciesControllerDeletePolicyV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type PoliciesControllerDeletePolicyV1AuthType = ClosedEnum<
  typeof PoliciesControllerDeletePolicyV1AuthType
>;

export const PoliciesControllerDeletePolicyV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]).describe("How the request was authenticated");

export type PoliciesControllerDeletePolicyV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
};

export const PoliciesControllerDeletePolicyV1Request$zodSchema: z.ZodType<
  PoliciesControllerDeletePolicyV1Request
> = z.object({
  id: z.string().describe("Policy ID"),
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});

export type DeletedPolicy = {
  id?: string | undefined;
  name?: string | undefined;
};

export const DeletedPolicy$zodSchema: z.ZodType<DeletedPolicy> = z.object({
  id: z.string().optional().describe("The deleted policy ID"),
  name: z.string().optional().describe("The deleted policy name"),
});

/**
 * Policy deleted successfully
 */
export type PoliciesControllerDeletePolicyV1ResponseBody = {
  success?: boolean | undefined;
  deletedPolicy?: DeletedPolicy | undefined;
  authType?: PoliciesControllerDeletePolicyV1AuthType | undefined;
};

export const PoliciesControllerDeletePolicyV1ResponseBody$zodSchema: z.ZodType<
  PoliciesControllerDeletePolicyV1ResponseBody
> = z.object({
  authType: PoliciesControllerDeletePolicyV1AuthType$zodSchema.optional()
    .describe("How the request was authenticated"),
  deletedPolicy: z.lazy(() => DeletedPolicy$zodSchema).optional(),
  success: z.boolean().optional().describe("Indicates successful deletion"),
}).describe("Policy deleted successfully");

export type PoliciesControllerDeletePolicyV1Response =
  | ApiErrorResponseDto
  | PoliciesControllerDeletePolicyV1ResponseBody;

export const PoliciesControllerDeletePolicyV1Response$zodSchema: z.ZodType<
  PoliciesControllerDeletePolicyV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => PoliciesControllerDeletePolicyV1ResponseBody$zodSchema),
]);
