/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type PoliciesControllerSetActivePolicyVersionV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  versionId: string;
};

export const PoliciesControllerSetActivePolicyVersionV1Request$zodSchema:
  z.ZodType<PoliciesControllerSetActivePolicyVersionV1Request> = z.object({
    id: z.string().describe("Policy ID"),
    versionId: z.string().describe("Policy version ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

/**
 * Active version updated
 */
export type PoliciesControllerSetActivePolicyVersionV1ResponseBody = {
  versionId?: string | undefined;
  version?: number | undefined;
};

export const PoliciesControllerSetActivePolicyVersionV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerSetActivePolicyVersionV1ResponseBody> = z.object({
    version: z.number().optional(),
    versionId: z.string().optional(),
  }).describe("Active version updated");

export type PoliciesControllerSetActivePolicyVersionV1Response =
  | ApiErrorResponseDto
  | PoliciesControllerSetActivePolicyVersionV1ResponseBody;

export const PoliciesControllerSetActivePolicyVersionV1Response$zodSchema:
  z.ZodType<PoliciesControllerSetActivePolicyVersionV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      PoliciesControllerSetActivePolicyVersionV1ResponseBody$zodSchema
    ),
  ]);
