/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  PublishVersionDto,
  PublishVersionDto$zodSchema,
} from "./publishversiondto.js";

export type PoliciesControllerPublishPolicyVersionV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  body: PublishVersionDto;
};

export const PoliciesControllerPublishPolicyVersionV1Request$zodSchema:
  z.ZodType<PoliciesControllerPublishPolicyVersionV1Request> = z.object({
    body: PublishVersionDto$zodSchema.describe("Publish a new policy version"),
    id: z.string().describe("Policy ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

/**
 * Version published
 */
export type PoliciesControllerPublishPolicyVersionV1ResponseBody = {
  versionId?: string | undefined;
  version?: number | undefined;
};

export const PoliciesControllerPublishPolicyVersionV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerPublishPolicyVersionV1ResponseBody> = z.object({
    version: z.number().optional(),
    versionId: z.string().optional(),
  }).describe("Version published");

export type PoliciesControllerPublishPolicyVersionV1Response =
  | ApiErrorResponseDto
  | PoliciesControllerPublishPolicyVersionV1ResponseBody;

export const PoliciesControllerPublishPolicyVersionV1Response$zodSchema:
  z.ZodType<PoliciesControllerPublishPolicyVersionV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      PoliciesControllerPublishPolicyVersionV1ResponseBody$zodSchema
    ),
  ]);
