/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  UpdateVersionContentDto,
  UpdateVersionContentDto$zodSchema,
} from "./updateversioncontentdto.js";

export type PoliciesControllerUpdateVersionContentV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  versionId: string;
  body: UpdateVersionContentDto;
};

export const PoliciesControllerUpdateVersionContentV1Request$zodSchema:
  z.ZodType<PoliciesControllerUpdateVersionContentV1Request> = z.object({
    body: UpdateVersionContentDto$zodSchema.describe(
      "Update content for a policy version",
    ),
    id: z.string().describe("Policy ID"),
    versionId: z.string().describe("Policy version ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

/**
 * Version content updated
 */
export type PoliciesControllerUpdateVersionContentV1ResponseBody = {
  versionId?: string | undefined;
};

export const PoliciesControllerUpdateVersionContentV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerUpdateVersionContentV1ResponseBody> = z.object({
    versionId: z.string().optional(),
  }).describe("Version content updated");

export type PoliciesControllerUpdateVersionContentV1Response =
  | ApiErrorResponseDto
  | PoliciesControllerUpdateVersionContentV1ResponseBody;

export const PoliciesControllerUpdateVersionContentV1Response$zodSchema:
  z.ZodType<PoliciesControllerUpdateVersionContentV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      PoliciesControllerUpdateVersionContentV1ResponseBody$zodSchema
    ),
  ]);
