/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  CreatePolicyVersionDto,
  CreatePolicyVersionDto$zodSchema,
} from "./createpolicyversiondto.js";

export type PoliciesControllerCreatePolicyVersionV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  body: CreatePolicyVersionDto;
};

export const PoliciesControllerCreatePolicyVersionV1Request$zodSchema:
  z.ZodType<PoliciesControllerCreatePolicyVersionV1Request> = z.object({
    body: CreatePolicyVersionDto$zodSchema.describe(
      "Create a new policy version draft",
    ),
    id: z.string().describe("Policy ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

/**
 * Policy version created
 */
export type PoliciesControllerCreatePolicyVersionV1ResponseBody = {
  versionId?: string | undefined;
  version?: number | undefined;
};

export const PoliciesControllerCreatePolicyVersionV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerCreatePolicyVersionV1ResponseBody> = z.object({
    version: z.number().optional(),
    versionId: z.string().optional(),
  }).describe("Policy version created");

export type PoliciesControllerCreatePolicyVersionV1Response =
  | ApiErrorResponseDto
  | PoliciesControllerCreatePolicyVersionV1ResponseBody;

export const PoliciesControllerCreatePolicyVersionV1Response$zodSchema:
  z.ZodType<PoliciesControllerCreatePolicyVersionV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() => PoliciesControllerCreatePolicyVersionV1ResponseBody$zodSchema),
  ]);
