/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  PolicyResponseDto,
  PolicyResponseDto$zodSchema,
} from "./policyresponsedto.js";
import {
  UpdatePolicyDto,
  UpdatePolicyDto$zodSchema,
} from "./updatepolicydto.js";

export type PoliciesControllerUpdatePolicyV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  body: UpdatePolicyDto;
};

export const PoliciesControllerUpdatePolicyV1Request$zodSchema: z.ZodType<
  PoliciesControllerUpdatePolicyV1Request
> = z.object({
  body: UpdatePolicyDto$zodSchema.describe("Policy update data"),
  id: z.string().describe("Policy ID"),
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});

export type PoliciesControllerUpdatePolicyV1Response =
  | PolicyResponseDto
  | ApiErrorResponseDto;

export const PoliciesControllerUpdatePolicyV1Response$zodSchema: z.ZodType<
  PoliciesControllerUpdatePolicyV1Response
> = z.union([
  PolicyResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
