/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type PoliciesControllerGetPolicyVersionByIdV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  versionId: string;
};

export const PoliciesControllerGetPolicyVersionByIdV1Request$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1Request> = z.object({
    id: z.string().describe("Policy ID"),
    versionId: z.string().describe("Policy version ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

export type PoliciesControllerGetPolicyVersionByIdV1Version = {};

export const PoliciesControllerGetPolicyVersionByIdV1Version$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1Version> = z.object({});

/**
 * Policy version retrieved successfully
 */
export type PoliciesControllerGetPolicyVersionByIdV1ResponseBody = {
  version?: PoliciesControllerGetPolicyVersionByIdV1Version | undefined;
  currentVersionId?: string | null | undefined;
  pendingVersionId?: string | null | undefined;
};

export const PoliciesControllerGetPolicyVersionByIdV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1ResponseBody> = z.object({
    currentVersionId: z.string().nullable().optional(),
    pendingVersionId: z.string().nullable().optional(),
    version: z.lazy(() =>
      PoliciesControllerGetPolicyVersionByIdV1Version$zodSchema
    ).optional(),
  }).describe("Policy version retrieved successfully");

export type PoliciesControllerGetPolicyVersionByIdV1Response =
  | ApiErrorResponseDto
  | PoliciesControllerGetPolicyVersionByIdV1ResponseBody;

export const PoliciesControllerGetPolicyVersionByIdV1Response$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      PoliciesControllerGetPolicyVersionByIdV1ResponseBody$zodSchema
    ),
  ]);
