/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type PoliciesControllerDeletePolicyVersionV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  versionId: string;
};

export const PoliciesControllerDeletePolicyVersionV1Request$zodSchema:
  z.ZodType<PoliciesControllerDeletePolicyVersionV1Request> = z.object({
    id: z.string().describe("Policy ID"),
    versionId: z.string().describe("Policy version ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

/**
 * Version deleted
 */
export type PoliciesControllerDeletePolicyVersionV1ResponseBody = {
  deletedVersion?: number | undefined;
};

export const PoliciesControllerDeletePolicyVersionV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerDeletePolicyVersionV1ResponseBody> = z.object({
    deletedVersion: z.number().optional(),
  }).describe("Version deleted");

export type PoliciesControllerDeletePolicyVersionV1Response =
  | ApiErrorResponseDto
  | PoliciesControllerDeletePolicyVersionV1ResponseBody;

export const PoliciesControllerDeletePolicyVersionV1Response$zodSchema:
  z.ZodType<PoliciesControllerDeletePolicyVersionV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() => PoliciesControllerDeletePolicyVersionV1ResponseBody$zodSchema),
  ]);
