/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  PolicyResponseDto,
  PolicyResponseDto$zodSchema,
} from "./policyresponsedto.js";

export type PoliciesControllerGetPolicyV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
};

export const PoliciesControllerGetPolicyV1Request$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyV1Request
> = z.object({
  id: z.string().describe("Policy ID"),
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});

export type PoliciesControllerGetPolicyV1Response =
  | PolicyResponseDto
  | ApiErrorResponseDto;

export const PoliciesControllerGetPolicyV1Response$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyV1Response
> = z.union([
  PolicyResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
