/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  SubmitForApprovalDto,
  SubmitForApprovalDto$zodSchema,
} from "./submitforapprovaldto.js";

export type PoliciesControllerSubmitVersionForApprovalV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  versionId: string;
  body: SubmitForApprovalDto;
};

export const PoliciesControllerSubmitVersionForApprovalV1Request$zodSchema:
  z.ZodType<PoliciesControllerSubmitVersionForApprovalV1Request> = z.object({
    body: SubmitForApprovalDto$zodSchema.describe(
      "Submit a policy version for approval",
    ),
    id: z.string().describe("Policy ID"),
    versionId: z.string().describe("Policy version ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

/**
 * Version submitted for approval
 */
export type PoliciesControllerSubmitVersionForApprovalV1ResponseBody = {
  versionId?: string | undefined;
  version?: number | undefined;
};

export const PoliciesControllerSubmitVersionForApprovalV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerSubmitVersionForApprovalV1ResponseBody> = z
    .object({
      version: z.number().optional(),
      versionId: z.string().optional(),
    }).describe("Version submitted for approval");

export type PoliciesControllerSubmitVersionForApprovalV1Response =
  | ApiErrorResponseDto
  | PoliciesControllerSubmitVersionForApprovalV1ResponseBody;

export const PoliciesControllerSubmitVersionForApprovalV1Response$zodSchema:
  z.ZodType<PoliciesControllerSubmitVersionForApprovalV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      PoliciesControllerSubmitVersionForApprovalV1ResponseBody$zodSchema
    ),
  ]);
