/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type PoliciesControllerGetPolicyVersionsV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
};

export const PoliciesControllerGetPolicyVersionsV1Request$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyVersionsV1Request
> = z.object({
  id: z.string().describe("Policy ID"),
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});

export type PoliciesControllerGetPolicyVersionsV1Version = {};

export const PoliciesControllerGetPolicyVersionsV1Version$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyVersionsV1Version
> = z.object({});

/**
 * Policy versions retrieved successfully
 */
export type PoliciesControllerGetPolicyVersionsV1ResponseBody = {
  versions?: Array<PoliciesControllerGetPolicyVersionsV1Version> | undefined;
  currentVersionId?: string | null | undefined;
  pendingVersionId?: string | null | undefined;
};

export const PoliciesControllerGetPolicyVersionsV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionsV1ResponseBody> = z.object({
    currentVersionId: z.string().nullable().optional(),
    pendingVersionId: z.string().nullable().optional(),
    versions: z.array(
      z.lazy(() => PoliciesControllerGetPolicyVersionsV1Version$zodSchema),
    ).optional(),
  }).describe("Policy versions retrieved successfully");

export type PoliciesControllerGetPolicyVersionsV1Response =
  | ApiErrorResponseDto
  | PoliciesControllerGetPolicyVersionsV1ResponseBody;

export const PoliciesControllerGetPolicyVersionsV1Response$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyVersionsV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => PoliciesControllerGetPolicyVersionsV1ResponseBody$zodSchema),
]);
