/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

/**
 * How the request was authenticated
 */
export const RisksControllerDeleteRiskV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type RisksControllerDeleteRiskV1AuthType = ClosedEnum<
  typeof RisksControllerDeleteRiskV1AuthType
>;

export const RisksControllerDeleteRiskV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]).describe("How the request was authenticated");

export type RisksControllerDeleteRiskV1Request = { id: string };

export const RisksControllerDeleteRiskV1Request$zodSchema: z.ZodType<
  RisksControllerDeleteRiskV1Request
> = z.object({
  id: z.string().describe("Risk ID"),
});

export type DeletedRisk = {
  id?: string | undefined;
  title?: string | undefined;
};

export const DeletedRisk$zodSchema: z.ZodType<DeletedRisk> = z.object({
  id: z.string().optional().describe("Deleted risk ID"),
  title: z.string().optional().describe("Deleted risk title"),
});

/**
 * User information (only for session auth)
 */
export type RisksControllerDeleteRiskV1AuthenticatedUser = {
  id?: string | undefined;
  email?: string | undefined;
};

export const RisksControllerDeleteRiskV1AuthenticatedUser$zodSchema: z.ZodType<
  RisksControllerDeleteRiskV1AuthenticatedUser
> = z.object({
  email: z.string().optional(),
  id: z.string().optional(),
}).describe("User information (only for session auth)");

/**
 * Risk deleted successfully
 */
export type RisksControllerDeleteRiskV1ResponseBody = {
  message?: string | undefined;
  deletedRisk?: DeletedRisk | undefined;
  authType?: RisksControllerDeleteRiskV1AuthType | undefined;
  authenticatedUser?: RisksControllerDeleteRiskV1AuthenticatedUser | undefined;
};

export const RisksControllerDeleteRiskV1ResponseBody$zodSchema: z.ZodType<
  RisksControllerDeleteRiskV1ResponseBody
> = z.object({
  authType: RisksControllerDeleteRiskV1AuthType$zodSchema.optional().describe(
    "How the request was authenticated",
  ),
  authenticatedUser: z.lazy(() =>
    RisksControllerDeleteRiskV1AuthenticatedUser$zodSchema
  ).optional().describe("User information (only for session auth)"),
  deletedRisk: z.lazy(() => DeletedRisk$zodSchema).optional(),
  message: z.string().optional(),
}).describe("Risk deleted successfully");

export type RisksControllerDeleteRiskV1Response =
  | ApiErrorResponseDto
  | RisksControllerDeleteRiskV1ResponseBody;

export const RisksControllerDeleteRiskV1Response$zodSchema: z.ZodType<
  RisksControllerDeleteRiskV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => RisksControllerDeleteRiskV1ResponseBody$zodSchema),
]);
