/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

/**
 * Residual likelihood frozen at acceptance
 */
export const RiskAcceptancesControllerListRiskAcceptancesV1ResidualLikelihood =
  {
    VeryUnlikely: "very_unlikely",
    Unlikely: "unlikely",
    Possible: "possible",
    Likely: "likely",
    VeryLikely: "very_likely",
  } as const;
/**
 * Residual likelihood frozen at acceptance
 */
export type RiskAcceptancesControllerListRiskAcceptancesV1ResidualLikelihood =
  ClosedEnum<
    typeof RiskAcceptancesControllerListRiskAcceptancesV1ResidualLikelihood
  >;

export const RiskAcceptancesControllerListRiskAcceptancesV1ResidualLikelihood$zodSchema =
  z.enum([
    "very_unlikely",
    "unlikely",
    "possible",
    "likely",
    "very_likely",
  ]).describe("Residual likelihood frozen at acceptance");

/**
 * Residual impact frozen at acceptance
 */
export const RiskAcceptancesControllerListRiskAcceptancesV1ResidualImpact = {
  Insignificant: "insignificant",
  Minor: "minor",
  Moderate: "moderate",
  Major: "major",
  Severe: "severe",
} as const;
/**
 * Residual impact frozen at acceptance
 */
export type RiskAcceptancesControllerListRiskAcceptancesV1ResidualImpact =
  ClosedEnum<
    typeof RiskAcceptancesControllerListRiskAcceptancesV1ResidualImpact
  >;

export const RiskAcceptancesControllerListRiskAcceptancesV1ResidualImpact$zodSchema =
  z.enum([
    "insignificant",
    "minor",
    "moderate",
    "major",
    "severe",
  ]).describe("Residual impact frozen at acceptance");

/**
 * Risk level of the accepted residual rating
 */
export const RiskAcceptancesControllerListRiskAcceptancesV1Level = {
  VeryLow: "very-low",
  Low: "low",
  Medium: "medium",
  High: "high",
  VeryHigh: "very-high",
} as const;
/**
 * Risk level of the accepted residual rating
 */
export type RiskAcceptancesControllerListRiskAcceptancesV1Level = ClosedEnum<
  typeof RiskAcceptancesControllerListRiskAcceptancesV1Level
>;

export const RiskAcceptancesControllerListRiskAcceptancesV1Level$zodSchema = z
  .enum([
    "very-low",
    "low",
    "medium",
    "high",
    "very-high",
  ]).describe("Risk level of the accepted residual rating");

/**
 * How the request was authenticated
 */
export const RiskAcceptancesControllerListRiskAcceptancesV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
  Service: "service",
} as const;
/**
 * How the request was authenticated
 */
export type RiskAcceptancesControllerListRiskAcceptancesV1AuthType = ClosedEnum<
  typeof RiskAcceptancesControllerListRiskAcceptancesV1AuthType
>;

export const RiskAcceptancesControllerListRiskAcceptancesV1AuthType$zodSchema =
  z.enum([
    "api-key",
    "session",
    "service",
  ]).describe("How the request was authenticated");

export type RiskAcceptancesControllerListRiskAcceptancesV1Request = {
  id: string;
};

export const RiskAcceptancesControllerListRiskAcceptancesV1Request$zodSchema:
  z.ZodType<RiskAcceptancesControllerListRiskAcceptancesV1Request> = z.object({
    id: z.string().describe("Risk ID"),
  });

export type RiskAcceptancesControllerListRiskAcceptancesV1Data = {
  id?: string | undefined;
  acceptedById?: string | null | undefined;
  acceptedByName?: string | undefined;
  notes?: string | null | undefined;
  residualLikelihood?:
    | RiskAcceptancesControllerListRiskAcceptancesV1ResidualLikelihood
    | undefined;
  residualImpact?:
    | RiskAcceptancesControllerListRiskAcceptancesV1ResidualImpact
    | undefined;
  level?: RiskAcceptancesControllerListRiskAcceptancesV1Level | undefined;
  levelLabel?: string | undefined;
  stale?: boolean | undefined;
  createdAt?: string | undefined;
};

export const RiskAcceptancesControllerListRiskAcceptancesV1Data$zodSchema:
  z.ZodType<RiskAcceptancesControllerListRiskAcceptancesV1Data> = z.object({
    acceptedById: z.string().nullable().optional().describe(
      "Member ID of the acceptor (null if since removed)",
    ),
    acceptedByName: z.string().optional().describe(
      "Acceptor display name, frozen at acceptance",
    ),
    createdAt: z.iso.datetime({ offset: true }).optional().describe(
      "When the acceptance was recorded (server-set, immutable)",
    ),
    id: z.string().optional().describe("Acceptance event ID"),
    level: RiskAcceptancesControllerListRiskAcceptancesV1Level$zodSchema
      .optional().describe("Risk level of the accepted residual rating"),
    levelLabel: z.string().optional().describe("Human-readable level label"),
    notes: z.string().nullable().optional(),
    residualImpact:
      RiskAcceptancesControllerListRiskAcceptancesV1ResidualImpact$zodSchema
        .optional().describe("Residual impact frozen at acceptance"),
    residualLikelihood:
      RiskAcceptancesControllerListRiskAcceptancesV1ResidualLikelihood$zodSchema
        .optional().describe("Residual likelihood frozen at acceptance"),
    stale: z.boolean().optional().describe(
      "True when the residual rating changed after this acceptance was recorded — re-acceptance is required",
    ),
  });

/**
 * User information (only for session auth)
 */
export type RiskAcceptancesControllerListRiskAcceptancesV1AuthenticatedUser = {
  id?: string | undefined;
  email?: string | undefined;
};

export const RiskAcceptancesControllerListRiskAcceptancesV1AuthenticatedUser$zodSchema:
  z.ZodType<RiskAcceptancesControllerListRiskAcceptancesV1AuthenticatedUser> = z
    .object({
      email: z.string().optional(),
      id: z.string().optional(),
    }).describe("User information (only for session auth)");

/**
 * Acceptance history retrieved successfully (newest first)
 */
export type RiskAcceptancesControllerListRiskAcceptancesV1ResponseBody = {
  data?: Array<RiskAcceptancesControllerListRiskAcceptancesV1Data> | undefined;
  authType?: RiskAcceptancesControllerListRiskAcceptancesV1AuthType | undefined;
  authenticatedUser?:
    | RiskAcceptancesControllerListRiskAcceptancesV1AuthenticatedUser
    | undefined;
};

export const RiskAcceptancesControllerListRiskAcceptancesV1ResponseBody$zodSchema:
  z.ZodType<RiskAcceptancesControllerListRiskAcceptancesV1ResponseBody> = z
    .object({
      authType: RiskAcceptancesControllerListRiskAcceptancesV1AuthType$zodSchema
        .optional().describe("How the request was authenticated"),
      authenticatedUser: z.lazy(() =>
        RiskAcceptancesControllerListRiskAcceptancesV1AuthenticatedUser$zodSchema
      ).optional().describe("User information (only for session auth)"),
      data: z.array(
        z.lazy(() =>
          RiskAcceptancesControllerListRiskAcceptancesV1Data$zodSchema
        ),
      ).optional(),
    }).describe("Acceptance history retrieved successfully (newest first)");

export type RiskAcceptancesControllerListRiskAcceptancesV1Response =
  | ApiErrorResponseDto
  | RiskAcceptancesControllerListRiskAcceptancesV1ResponseBody;

export const RiskAcceptancesControllerListRiskAcceptancesV1Response$zodSchema:
  z.ZodType<RiskAcceptancesControllerListRiskAcceptancesV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      RiskAcceptancesControllerListRiskAcceptancesV1ResponseBody$zodSchema
    ),
  ]);
