/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  CreateRiskAcceptanceDto,
  CreateRiskAcceptanceDto$zodSchema,
} from "./createriskacceptancedto.js";

/**
 * Residual likelihood frozen at acceptance
 */
export const RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualLikelihood =
  {
    VeryUnlikely: "very_unlikely",
    Unlikely: "unlikely",
    Possible: "possible",
    Likely: "likely",
    VeryLikely: "very_likely",
  } as const;
/**
 * Residual likelihood frozen at acceptance
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualLikelihood =
  ClosedEnum<
    typeof RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualLikelihood
  >;

export const RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualLikelihood$zodSchema =
  z.enum([
    "very_unlikely",
    "unlikely",
    "possible",
    "likely",
    "very_likely",
  ]).describe("Residual likelihood frozen at acceptance");

/**
 * Residual impact frozen at acceptance
 */
export const RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualImpact = {
  Insignificant: "insignificant",
  Minor: "minor",
  Moderate: "moderate",
  Major: "major",
  Severe: "severe",
} as const;
/**
 * Residual impact frozen at acceptance
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualImpact =
  ClosedEnum<
    typeof RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualImpact
  >;

export const RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualImpact$zodSchema =
  z.enum([
    "insignificant",
    "minor",
    "moderate",
    "major",
    "severe",
  ]).describe("Residual impact frozen at acceptance");

/**
 * Risk level of the accepted residual rating
 */
export const RiskAcceptancesControllerRecordRiskAcceptanceV1Level = {
  VeryLow: "very-low",
  Low: "low",
  Medium: "medium",
  High: "high",
  VeryHigh: "very-high",
} as const;
/**
 * Risk level of the accepted residual rating
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1Level = ClosedEnum<
  typeof RiskAcceptancesControllerRecordRiskAcceptanceV1Level
>;

export const RiskAcceptancesControllerRecordRiskAcceptanceV1Level$zodSchema = z
  .enum([
    "very-low",
    "low",
    "medium",
    "high",
    "very-high",
  ]).describe("Risk level of the accepted residual rating");

/**
 * How the request was authenticated
 */
export const RiskAcceptancesControllerRecordRiskAcceptanceV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
  Service: "service",
} as const;
/**
 * How the request was authenticated
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1AuthType =
  ClosedEnum<typeof RiskAcceptancesControllerRecordRiskAcceptanceV1AuthType>;

export const RiskAcceptancesControllerRecordRiskAcceptanceV1AuthType$zodSchema =
  z.enum([
    "api-key",
    "session",
    "service",
  ]).describe("How the request was authenticated");

export type RiskAcceptancesControllerRecordRiskAcceptanceV1Request = {
  id: string;
  body: CreateRiskAcceptanceDto;
};

export const RiskAcceptancesControllerRecordRiskAcceptanceV1Request$zodSchema:
  z.ZodType<RiskAcceptancesControllerRecordRiskAcceptanceV1Request> = z.object({
    body: CreateRiskAcceptanceDto$zodSchema.describe(
      "Acceptance data (acceptor defaults to the risk owner)",
    ),
    id: z.string().describe("Risk ID"),
  });

/**
 * Internal server error
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1InternalServerErrorResponseBody =
  { message?: string | undefined };

export const RiskAcceptancesControllerRecordRiskAcceptanceV1InternalServerErrorResponseBody$zodSchema:
  z.ZodType<
    RiskAcceptancesControllerRecordRiskAcceptanceV1InternalServerErrorResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Internal server error");

/**
 * Risk not found
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1NotFoundResponseBody =
  { message?: string | undefined };

export const RiskAcceptancesControllerRecordRiskAcceptanceV1NotFoundResponseBody$zodSchema:
  z.ZodType<
    RiskAcceptancesControllerRecordRiskAcceptanceV1NotFoundResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Risk not found");

/**
 * Forbidden - User does not have permission to access this risk
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1ForbiddenResponseBody =
  { message?: string | undefined };

export const RiskAcceptancesControllerRecordRiskAcceptanceV1ForbiddenResponseBody$zodSchema:
  z.ZodType<
    RiskAcceptancesControllerRecordRiskAcceptanceV1ForbiddenResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Forbidden - User does not have permission to access this risk");

/**
 * Unauthorized - Invalid authentication
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1UnauthorizedResponseBody =
  { message?: string | undefined };

export const RiskAcceptancesControllerRecordRiskAcceptanceV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<
    RiskAcceptancesControllerRecordRiskAcceptanceV1UnauthorizedResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Unauthorized - Invalid authentication");

/**
 * No owner assigned, or the acceptor is not a valid member
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1BadRequestResponseBody =
  { message?: string | undefined };

export const RiskAcceptancesControllerRecordRiskAcceptanceV1BadRequestResponseBody$zodSchema:
  z.ZodType<
    RiskAcceptancesControllerRecordRiskAcceptanceV1BadRequestResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("No owner assigned, or the acceptor is not a valid member");

/**
 * User information (only for session auth)
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1AuthenticatedUser = {
  id?: string | undefined;
  email?: string | undefined;
};

export const RiskAcceptancesControllerRecordRiskAcceptanceV1AuthenticatedUser$zodSchema:
  z.ZodType<RiskAcceptancesControllerRecordRiskAcceptanceV1AuthenticatedUser> =
    z.object({
      email: z.string().optional(),
      id: z.string().optional(),
    }).describe("User information (only for session auth)");

/**
 * Acceptance recorded successfully
 */
export type RiskAcceptancesControllerRecordRiskAcceptanceV1ResponseBody = {
  id?: string | undefined;
  acceptedById?: string | null | undefined;
  acceptedByName?: string | undefined;
  notes?: string | null | undefined;
  residualLikelihood?:
    | RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualLikelihood
    | undefined;
  residualImpact?:
    | RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualImpact
    | undefined;
  level?: RiskAcceptancesControllerRecordRiskAcceptanceV1Level | undefined;
  levelLabel?: string | undefined;
  stale?: boolean | undefined;
  createdAt?: string | undefined;
  authType?:
    | RiskAcceptancesControllerRecordRiskAcceptanceV1AuthType
    | undefined;
  authenticatedUser?:
    | RiskAcceptancesControllerRecordRiskAcceptanceV1AuthenticatedUser
    | undefined;
};

export const RiskAcceptancesControllerRecordRiskAcceptanceV1ResponseBody$zodSchema:
  z.ZodType<RiskAcceptancesControllerRecordRiskAcceptanceV1ResponseBody> = z
    .object({
      acceptedById: z.string().nullable().optional().describe(
        "Member ID of the acceptor (null if since removed)",
      ),
      acceptedByName: z.string().optional().describe(
        "Acceptor display name, frozen at acceptance",
      ),
      authType:
        RiskAcceptancesControllerRecordRiskAcceptanceV1AuthType$zodSchema
          .optional().describe("How the request was authenticated"),
      authenticatedUser: z.lazy(() =>
        RiskAcceptancesControllerRecordRiskAcceptanceV1AuthenticatedUser$zodSchema
      ).optional().describe("User information (only for session auth)"),
      createdAt: z.iso.datetime({ offset: true }).optional().describe(
        "When the acceptance was recorded (server-set, immutable)",
      ),
      id: z.string().optional().describe("Acceptance event ID"),
      level: RiskAcceptancesControllerRecordRiskAcceptanceV1Level$zodSchema
        .optional().describe("Risk level of the accepted residual rating"),
      levelLabel: z.string().optional().describe("Human-readable level label"),
      notes: z.string().nullable().optional(),
      residualImpact:
        RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualImpact$zodSchema
          .optional().describe("Residual impact frozen at acceptance"),
      residualLikelihood:
        RiskAcceptancesControllerRecordRiskAcceptanceV1ResidualLikelihood$zodSchema
          .optional().describe("Residual likelihood frozen at acceptance"),
      stale: z.boolean().optional().describe(
        "True when the residual rating changed after this acceptance was recorded — re-acceptance is required",
      ),
    }).describe("Acceptance recorded successfully");

export type RiskAcceptancesControllerRecordRiskAcceptanceV1Response =
  | RiskAcceptancesControllerRecordRiskAcceptanceV1ResponseBody
  | RiskAcceptancesControllerRecordRiskAcceptanceV1BadRequestResponseBody
  | RiskAcceptancesControllerRecordRiskAcceptanceV1UnauthorizedResponseBody
  | RiskAcceptancesControllerRecordRiskAcceptanceV1ForbiddenResponseBody
  | RiskAcceptancesControllerRecordRiskAcceptanceV1NotFoundResponseBody
  | RiskAcceptancesControllerRecordRiskAcceptanceV1InternalServerErrorResponseBody;

export const RiskAcceptancesControllerRecordRiskAcceptanceV1Response$zodSchema:
  z.ZodType<RiskAcceptancesControllerRecordRiskAcceptanceV1Response> = z.union([
    z.lazy(() =>
      RiskAcceptancesControllerRecordRiskAcceptanceV1ResponseBody$zodSchema
    ),
    z.lazy(() =>
      RiskAcceptancesControllerRecordRiskAcceptanceV1BadRequestResponseBody$zodSchema
    ),
    z.lazy(() =>
      RiskAcceptancesControllerRecordRiskAcceptanceV1UnauthorizedResponseBody$zodSchema
    ),
    z.lazy(() =>
      RiskAcceptancesControllerRecordRiskAcceptanceV1ForbiddenResponseBody$zodSchema
    ),
    z.lazy(() =>
      RiskAcceptancesControllerRecordRiskAcceptanceV1NotFoundResponseBody$zodSchema
    ),
    z.lazy(() =>
      RiskAcceptancesControllerRecordRiskAcceptanceV1InternalServerErrorResponseBody$zodSchema
    ),
  ]);
