/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  AttachmentResponseDto,
  AttachmentResponseDto$zodSchema,
} from "./attachmentresponsedto.js";
import {
  UploadAttachmentDto,
  UploadAttachmentDto$zodSchema,
} from "./uploadattachmentdto.js";

export type TasksControllerUploadTaskAttachmentV1Request = {
  taskId: string;
  body: UploadAttachmentDto;
};

export const TasksControllerUploadTaskAttachmentV1Request$zodSchema: z.ZodType<
  TasksControllerUploadTaskAttachmentV1Request
> = z.object({
  body: UploadAttachmentDto$zodSchema,
  taskId: z.string().describe("Unique task identifier"),
});

export type TasksControllerUploadTaskAttachmentV1Response =
  | AttachmentResponseDto
  | ApiErrorResponseDto;

export const TasksControllerUploadTaskAttachmentV1Response$zodSchema: z.ZodType<
  TasksControllerUploadTaskAttachmentV1Response
> = z.union([
  AttachmentResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
