/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type TasksControllerDeleteTaskV1Request = { taskId: string };

export const TasksControllerDeleteTaskV1Request$zodSchema: z.ZodType<
  TasksControllerDeleteTaskV1Request
> = z.object({
  taskId: z.string().describe("Unique task identifier"),
});

/**
 * Task deleted successfully
 */
export type TasksControllerDeleteTaskV1ResponseBody = {
  success?: boolean | undefined;
  message?: string | undefined;
};

export const TasksControllerDeleteTaskV1ResponseBody$zodSchema: z.ZodType<
  TasksControllerDeleteTaskV1ResponseBody
> = z.object({
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Task deleted successfully");

export type TasksControllerDeleteTaskV1Response =
  | ApiErrorResponseDto
  | TasksControllerDeleteTaskV1ResponseBody;

export const TasksControllerDeleteTaskV1Response$zodSchema: z.ZodType<
  TasksControllerDeleteTaskV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => TasksControllerDeleteTaskV1ResponseBody$zodSchema),
]);
