/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  TaskResponseDto,
  TaskResponseDto$zodSchema,
} from "./taskresponsedto.js";

export type TasksControllerGetTasksV1Request = {
  includeRelations?: string | undefined;
};

export const TasksControllerGetTasksV1Request$zodSchema: z.ZodType<
  TasksControllerGetTasksV1Request
> = z.object({
  includeRelations: z.string().describe(
    "Include controls and automations with runs",
  ).optional(),
});

export type TasksControllerGetTasksV1Response =
  | ApiErrorResponseDto
  | Array<TaskResponseDto>;

export const TasksControllerGetTasksV1Response$zodSchema: z.ZodType<
  TasksControllerGetTasksV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.array(TaskResponseDto$zodSchema).describe("Tasks retrieved successfully"),
]);
