/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  TaskResponseDto,
  TaskResponseDto$zodSchema,
} from "./taskresponsedto.js";

export type TasksControllerGetTaskV1Request = { taskId: string };

export const TasksControllerGetTaskV1Request$zodSchema: z.ZodType<
  TasksControllerGetTaskV1Request
> = z.object({
  taskId: z.string().describe("Unique task identifier"),
});

export type TasksControllerGetTaskV1Response =
  | TaskResponseDto
  | ApiErrorResponseDto;

export const TasksControllerGetTaskV1Response$zodSchema: z.ZodType<
  TasksControllerGetTaskV1Response
> = z.union([
  TaskResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
