/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type TasksControllerUpdateTasksAssigneeV1Request = {
  taskIds: Array<string>;
  assigneeId?: string | null | undefined;
};

export const TasksControllerUpdateTasksAssigneeV1Request$zodSchema: z.ZodType<
  TasksControllerUpdateTasksAssigneeV1Request
> = z.object({
  assigneeId: z.string().nullable().optional().describe(
    "Assignee member ID, or null to unassign",
  ),
  taskIds: z.array(z.string()),
});

/**
 * Tasks updated successfully
 */
export type TasksControllerUpdateTasksAssigneeV1ResponseBody = {
  updatedCount?: number | undefined;
};

export const TasksControllerUpdateTasksAssigneeV1ResponseBody$zodSchema:
  z.ZodType<TasksControllerUpdateTasksAssigneeV1ResponseBody> = z.object({
    updatedCount: z.number().optional(),
  }).describe("Tasks updated successfully");

export type TasksControllerUpdateTasksAssigneeV1Response =
  | ApiErrorResponseDto
  | TasksControllerUpdateTasksAssigneeV1ResponseBody;

export const TasksControllerUpdateTasksAssigneeV1Response$zodSchema: z.ZodType<
  TasksControllerUpdateTasksAssigneeV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => TasksControllerUpdateTasksAssigneeV1ResponseBody$zodSchema),
]);
