/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export const TasksControllerUpdateTasksStatusV1Status = {
  Todo: "todo",
  InProgress: "in_progress",
  InReview: "in_review",
  Done: "done",
  NotRelevant: "not_relevant",
  Failed: "failed",
} as const;
export type TasksControllerUpdateTasksStatusV1Status = ClosedEnum<
  typeof TasksControllerUpdateTasksStatusV1Status
>;

export const TasksControllerUpdateTasksStatusV1Status$zodSchema = z.enum([
  "todo",
  "in_progress",
  "in_review",
  "done",
  "not_relevant",
  "failed",
]);

export type TasksControllerUpdateTasksStatusV1Request = {
  taskIds: Array<string>;
  status: TasksControllerUpdateTasksStatusV1Status;
  reviewDate?: string | undefined;
  notRelevantJustification?: string | undefined;
};

export const TasksControllerUpdateTasksStatusV1Request$zodSchema: z.ZodType<
  TasksControllerUpdateTasksStatusV1Request
> = z.object({
  notRelevantJustification: z.string().optional().describe(
    "Required justification when marking evidence tasks as not_relevant",
  ),
  reviewDate: z.iso.datetime({ offset: true }).optional().describe(
    "Optional review date to set on all tasks",
  ),
  status: TasksControllerUpdateTasksStatusV1Status$zodSchema,
  taskIds: z.array(z.string()),
});

/**
 * Tasks updated successfully
 */
export type TasksControllerUpdateTasksStatusV1ResponseBody = {
  updatedCount?: number | undefined;
};

export const TasksControllerUpdateTasksStatusV1ResponseBody$zodSchema:
  z.ZodType<TasksControllerUpdateTasksStatusV1ResponseBody> = z.object({
    updatedCount: z.number().optional(),
  }).describe("Tasks updated successfully");

export type TasksControllerUpdateTasksStatusV1Response =
  | ApiErrorResponseDto
  | TasksControllerUpdateTasksStatusV1ResponseBody;

export const TasksControllerUpdateTasksStatusV1Response$zodSchema: z.ZodType<
  TasksControllerUpdateTasksStatusV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => TasksControllerUpdateTasksStatusV1ResponseBody$zodSchema),
]);
