/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type TasksControllerGetTaskAttachmentDownloadUrlV1Request = {
  taskId: string;
  attachmentId: string;
};

export const TasksControllerGetTaskAttachmentDownloadUrlV1Request$zodSchema:
  z.ZodType<TasksControllerGetTaskAttachmentDownloadUrlV1Request> = z.object({
    attachmentId: z.string().describe("Unique attachment identifier"),
    taskId: z.string().describe("Unique task identifier"),
  });

/**
 * Download URL generated successfully
 */
export type TasksControllerGetTaskAttachmentDownloadUrlV1ResponseBody = {
  downloadUrl?: string | undefined;
  expiresIn?: number | undefined;
};

export const TasksControllerGetTaskAttachmentDownloadUrlV1ResponseBody$zodSchema:
  z.ZodType<TasksControllerGetTaskAttachmentDownloadUrlV1ResponseBody> = z
    .object({
      downloadUrl: z.string().optional().describe(
        "Signed URL for downloading the file",
      ),
      expiresIn: z.number().optional().describe(
        "URL expiration time in seconds",
      ),
    }).describe("Download URL generated successfully");

export type TasksControllerGetTaskAttachmentDownloadUrlV1Response =
  | ApiErrorResponseDto
  | TasksControllerGetTaskAttachmentDownloadUrlV1ResponseBody;

export const TasksControllerGetTaskAttachmentDownloadUrlV1Response$zodSchema:
  z.ZodType<TasksControllerGetTaskAttachmentDownloadUrlV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      TasksControllerGetTaskAttachmentDownloadUrlV1ResponseBody$zodSchema
    ),
  ]);
