/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  TaskItemResponseDto,
  TaskItemResponseDto$zodSchema,
} from "./taskitemresponsedto.js";
import {
  UpdateTaskItemDto,
  UpdateTaskItemDto$zodSchema,
} from "./updatetaskitemdto.js";

export type TaskManagementControllerUpdateTaskItemV1Request = {
  id: string;
  body: UpdateTaskItemDto;
};

export const TaskManagementControllerUpdateTaskItemV1Request$zodSchema:
  z.ZodType<TaskManagementControllerUpdateTaskItemV1Request> = z.object({
    body: UpdateTaskItemDto$zodSchema,
    id: z.string().describe("Task item ID"),
  });

export type TaskManagementControllerUpdateTaskItemV1Response =
  | TaskItemResponseDto
  | ApiErrorResponseDto;

export const TaskManagementControllerUpdateTaskItemV1Response$zodSchema:
  z.ZodType<TaskManagementControllerUpdateTaskItemV1Response> = z.union([
    TaskItemResponseDto$zodSchema,
    ApiErrorResponseDto$zodSchema,
  ]);
