/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  AttachmentResponseDto,
  AttachmentResponseDto$zodSchema,
} from "./attachmentresponsedto.js";

export type TasksControllerGetTaskAttachmentsV1Request = { taskId: string };

export const TasksControllerGetTaskAttachmentsV1Request$zodSchema: z.ZodType<
  TasksControllerGetTaskAttachmentsV1Request
> = z.object({
  taskId: z.string().describe("Unique task identifier"),
});

export type TasksControllerGetTaskAttachmentsV1Response =
  | ApiErrorResponseDto
  | Array<AttachmentResponseDto>;

export const TasksControllerGetTaskAttachmentsV1Response$zodSchema: z.ZodType<
  TasksControllerGetTaskAttachmentsV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.array(AttachmentResponseDto$zodSchema).describe(
    "Attachments retrieved successfully",
  ),
]);
