/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  TaskItemResponseDto,
  TaskItemResponseDto$zodSchema,
} from "./taskitemresponsedto.js";

export type TaskManagementControllerCreateTaskItemV1Response =
  | TaskItemResponseDto
  | ApiErrorResponseDto;

export const TaskManagementControllerCreateTaskItemV1Response$zodSchema:
  z.ZodType<TaskManagementControllerCreateTaskItemV1Response> = z.union([
    TaskItemResponseDto$zodSchema,
    ApiErrorResponseDto$zodSchema,
  ]);
