/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type TasksControllerDeleteTaskAttachmentV1Request = {
  taskId: string;
  attachmentId: string;
};

export const TasksControllerDeleteTaskAttachmentV1Request$zodSchema: z.ZodType<
  TasksControllerDeleteTaskAttachmentV1Request
> = z.object({
  attachmentId: z.string().describe("Unique attachment identifier"),
  taskId: z.string().describe("Unique task identifier"),
});

/**
 * Attachment deleted successfully
 */
export type TasksControllerDeleteTaskAttachmentV1ResponseBody = {
  success?: boolean | undefined;
  deletedAttachmentId?: string | undefined;
  message?: string | undefined;
};

export const TasksControllerDeleteTaskAttachmentV1ResponseBody$zodSchema:
  z.ZodType<TasksControllerDeleteTaskAttachmentV1ResponseBody> = z.object({
    deletedAttachmentId: z.string().optional(),
    message: z.string().optional(),
    success: z.boolean().optional(),
  }).describe("Attachment deleted successfully");

export type TasksControllerDeleteTaskAttachmentV1Response =
  | ApiErrorResponseDto
  | TasksControllerDeleteTaskAttachmentV1ResponseBody;

export const TasksControllerDeleteTaskAttachmentV1Response$zodSchema: z.ZodType<
  TasksControllerDeleteTaskAttachmentV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => TasksControllerDeleteTaskAttachmentV1ResponseBody$zodSchema),
]);
