/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TimelinesControllerMarkReadyForReviewV1Request = {
  id: string;
  phaseId: string;
};

export const TimelinesControllerMarkReadyForReviewV1Request$zodSchema:
  z.ZodType<TimelinesControllerMarkReadyForReviewV1Request> = z.object({
    id: z.string(),
    phaseId: z.string(),
  });
