/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  SendTrainingCompletionResponseDto,
  SendTrainingCompletionResponseDto$zodSchema,
} from "./sendtrainingcompletionresponsedto.js";

export type TrainingControllerSendTrainingCompletionEmailV1Response =
  | ApiErrorResponseDto
  | SendTrainingCompletionResponseDto;

export const TrainingControllerSendTrainingCompletionEmailV1Response$zodSchema:
  z.ZodType<TrainingControllerSendTrainingCompletionEmailV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    SendTrainingCompletionResponseDto$zodSchema,
  ]);
