/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TrustAccessControllerGetPublicFrameworksV1Request = {
  friendlyUrl: string;
};

export const TrustAccessControllerGetPublicFrameworksV1Request$zodSchema:
  z.ZodType<TrustAccessControllerGetPublicFrameworksV1Request> = z.object({
    friendlyUrl: z.string().describe(
      "Trust Portal friendly URL or Organization ID",
    ),
  });
