/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  CustomFrameworkBadgeResponseDto,
  CustomFrameworkBadgeResponseDto$zodSchema,
} from "./customframeworkbadgeresponsedto.js";

export type TrustPortalControllerUploadCustomFrameworkBadgeV1Response =
  | CustomFrameworkBadgeResponseDto
  | ApiErrorResponseDto;

export const TrustPortalControllerUploadCustomFrameworkBadgeV1Response$zodSchema:
  z.ZodType<TrustPortalControllerUploadCustomFrameworkBadgeV1Response> = z
    .union([
      CustomFrameworkBadgeResponseDto$zodSchema,
      ApiErrorResponseDto$zodSchema,
    ]);
