/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TrustAccessControllerStreamPreviewNdaV1Request = { id: string };

export const TrustAccessControllerStreamPreviewNdaV1Request$zodSchema:
  z.ZodType<TrustAccessControllerStreamPreviewNdaV1Request> = z.object({
    id: z.string(),
  });
