/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  DomainStatusResponseDto,
  DomainStatusResponseDto$zodSchema,
} from "./domainstatusresponsedto.js";

export type TrustPortalControllerGetDomainStatusV1Request = { domain: string };

export const TrustPortalControllerGetDomainStatusV1Request$zodSchema: z.ZodType<
  TrustPortalControllerGetDomainStatusV1Request
> = z.object({
  domain: z.string().describe("The domain name to check status for"),
});

export type TrustPortalControllerGetDomainStatusV1Response =
  | DomainStatusResponseDto
  | ApiErrorResponseDto;

export const TrustPortalControllerGetDomainStatusV1Response$zodSchema:
  z.ZodType<TrustPortalControllerGetDomainStatusV1Response> = z.union([
    DomainStatusResponseDto$zodSchema,
    ApiErrorResponseDto$zodSchema,
  ]);
