/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  TrustDocumentResponseDto,
  TrustDocumentResponseDto$zodSchema,
} from "./trustdocumentresponsedto.js";

export type TrustPortalControllerListTrustDocumentsV1Response =
  | ApiErrorResponseDto
  | Array<TrustDocumentResponseDto>;

export const TrustPortalControllerListTrustDocumentsV1Response$zodSchema:
  z.ZodType<TrustPortalControllerListTrustDocumentsV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.array(TrustDocumentResponseDto$zodSchema).describe(
      "Documents retrieved successfully",
    ),
  ]);
