/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  DeleteTrustDocumentDto,
  DeleteTrustDocumentDto$zodSchema,
} from "./deletetrustdocumentdto.js";

export type TrustPortalControllerDeleteTrustDocumentV1Request = {
  documentId: string;
  body: DeleteTrustDocumentDto;
};

export const TrustPortalControllerDeleteTrustDocumentV1Request$zodSchema:
  z.ZodType<TrustPortalControllerDeleteTrustDocumentV1Request> = z.object({
    body: DeleteTrustDocumentDto$zodSchema,
    documentId: z.string(),
  });

/**
 * Document deleted successfully
 */
export type TrustPortalControllerDeleteTrustDocumentV1ResponseBody = {
  success?: boolean | undefined;
};

export const TrustPortalControllerDeleteTrustDocumentV1ResponseBody$zodSchema:
  z.ZodType<TrustPortalControllerDeleteTrustDocumentV1ResponseBody> = z.object({
    success: z.boolean().optional(),
  }).describe("Document deleted successfully");

export type TrustPortalControllerDeleteTrustDocumentV1Response =
  | ApiErrorResponseDto
  | TrustPortalControllerDeleteTrustDocumentV1ResponseBody;

export const TrustPortalControllerDeleteTrustDocumentV1Response$zodSchema:
  z.ZodType<TrustPortalControllerDeleteTrustDocumentV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.lazy(() =>
      TrustPortalControllerDeleteTrustDocumentV1ResponseBody$zodSchema
    ),
  ]);
