/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  ComplianceResourceResponseDto,
  ComplianceResourceResponseDto$zodSchema,
} from "./complianceresourceresponsedto.js";

export type TrustPortalControllerUploadComplianceResourceV1Response =
  | ComplianceResourceResponseDto
  | ApiErrorResponseDto;

export const TrustPortalControllerUploadComplianceResourceV1Response$zodSchema:
  z.ZodType<TrustPortalControllerUploadComplianceResourceV1Response> = z.union([
    ComplianceResourceResponseDto$zodSchema,
    ApiErrorResponseDto$zodSchema,
  ]);
