/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

export type TrustAccessControllerGetPublicSecurityQuestionnaireV1Request = {
  friendlyUrl: string;
};

export const TrustAccessControllerGetPublicSecurityQuestionnaireV1Request$zodSchema:
  z.ZodType<TrustAccessControllerGetPublicSecurityQuestionnaireV1Request> = z
    .object({
      friendlyUrl: z.string().describe(
        "Trust Portal friendly URL or Organization ID",
      ),
    });

/**
 * Security Questionnaire visibility retrieved successfully
 */
export type TrustAccessControllerGetPublicSecurityQuestionnaireV1ResponseBody =
  { enabled?: boolean | undefined };

export const TrustAccessControllerGetPublicSecurityQuestionnaireV1ResponseBody$zodSchema:
  z.ZodType<TrustAccessControllerGetPublicSecurityQuestionnaireV1ResponseBody> =
    z.object({
      enabled: z.boolean().optional(),
    }).describe("Security Questionnaire visibility retrieved successfully");

export type TrustAccessControllerGetPublicSecurityQuestionnaireV1Response =
  | ApiErrorResponseDto
  | TrustAccessControllerGetPublicSecurityQuestionnaireV1ResponseBody;

export const TrustAccessControllerGetPublicSecurityQuestionnaireV1Response$zodSchema:
  z.ZodType<TrustAccessControllerGetPublicSecurityQuestionnaireV1Response> = z
    .union([
      ApiErrorResponseDto$zodSchema,
      z.lazy(() =>
        TrustAccessControllerGetPublicSecurityQuestionnaireV1ResponseBody$zodSchema
      ),
    ]);
