/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  TrustDocumentResponseDto,
  TrustDocumentResponseDto$zodSchema,
} from "./trustdocumentresponsedto.js";

export type TrustPortalControllerUploadTrustDocumentV1Response =
  | TrustDocumentResponseDto
  | ApiErrorResponseDto;

export const TrustPortalControllerUploadTrustDocumentV1Response$zodSchema:
  z.ZodType<TrustPortalControllerUploadTrustDocumentV1Response> = z.union([
    TrustDocumentResponseDto$zodSchema,
    ApiErrorResponseDto$zodSchema,
  ]);
