/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  ComplianceResourceResponseDto,
  ComplianceResourceResponseDto$zodSchema,
} from "./complianceresourceresponsedto.js";

export type TrustPortalControllerListComplianceResourcesV1Response =
  | ApiErrorResponseDto
  | Array<ComplianceResourceResponseDto>;

export const TrustPortalControllerListComplianceResourcesV1Response$zodSchema:
  z.ZodType<TrustPortalControllerListComplianceResourcesV1Response> = z.union([
    ApiErrorResponseDto$zodSchema,
    z.array(ComplianceResourceResponseDto$zodSchema).describe(
      "Compliance certificates retrieved successfully",
    ),
  ]);
