/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  ComplianceResourceUrlResponseDto,
  ComplianceResourceUrlResponseDto$zodSchema,
} from "./complianceresourceurlresponsedto.js";

export type TrustPortalControllerGetComplianceResourceUrlV1Response =
  | ComplianceResourceUrlResponseDto
  | ApiErrorResponseDto;

export const TrustPortalControllerGetComplianceResourceUrlV1Response$zodSchema:
  z.ZodType<TrustPortalControllerGetComplianceResourceUrlV1Response> = z.union([
    ComplianceResourceUrlResponseDto$zodSchema,
    ApiErrorResponseDto$zodSchema,
  ]);
