/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";
import {
  CreateUploadUrlDto,
  CreateUploadUrlDto$zodSchema,
} from "./createuploadurldto.js";
import {
  UploadUrlResponseDto,
  UploadUrlResponseDto$zodSchema,
} from "./uploadurlresponsedto.js";

export type UploadsControllerCreateUploadUrlV1Request = {
  xOrganizationId?: string | undefined;
  body: CreateUploadUrlDto;
};

export const UploadsControllerCreateUploadUrlV1Request$zodSchema: z.ZodType<
  UploadsControllerCreateUploadUrlV1Request
> = z.object({
  body: CreateUploadUrlDto$zodSchema,
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});

export type UploadsControllerCreateUploadUrlV1Response =
  | UploadUrlResponseDto
  | ApiErrorResponseDto;

export const UploadsControllerCreateUploadUrlV1Response$zodSchema: z.ZodType<
  UploadsControllerCreateUploadUrlV1Response
> = z.union([
  UploadUrlResponseDto$zodSchema,
  ApiErrorResponseDto$zodSchema,
]);
