/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorResponseDto,
  ApiErrorResponseDto$zodSchema,
} from "./apierrorresponsedto.js";

/**
 * How the request was authenticated
 */
export const VendorsControllerDeleteVendorV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type VendorsControllerDeleteVendorV1AuthType = ClosedEnum<
  typeof VendorsControllerDeleteVendorV1AuthType
>;

export const VendorsControllerDeleteVendorV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]).describe("How the request was authenticated");

export type VendorsControllerDeleteVendorV1Request = { id: string };

export const VendorsControllerDeleteVendorV1Request$zodSchema: z.ZodType<
  VendorsControllerDeleteVendorV1Request
> = z.object({
  id: z.string().describe("Vendor ID"),
});

export type DeletedVendor = {
  id?: string | undefined;
  name?: string | undefined;
};

export const DeletedVendor$zodSchema: z.ZodType<DeletedVendor> = z.object({
  id: z.string().optional().describe("Deleted vendor ID"),
  name: z.string().optional().describe("Deleted vendor name"),
});

/**
 * User information (only for session auth)
 */
export type VendorsControllerDeleteVendorV1AuthenticatedUser = {
  id?: string | undefined;
  email?: string | undefined;
};

export const VendorsControllerDeleteVendorV1AuthenticatedUser$zodSchema:
  z.ZodType<VendorsControllerDeleteVendorV1AuthenticatedUser> = z.object({
    email: z.string().optional(),
    id: z.string().optional(),
  }).describe("User information (only for session auth)");

/**
 * Vendor deleted successfully
 */
export type VendorsControllerDeleteVendorV1ResponseBody = {
  message?: string | undefined;
  deletedVendor?: DeletedVendor | undefined;
  authType?: VendorsControllerDeleteVendorV1AuthType | undefined;
  authenticatedUser?:
    | VendorsControllerDeleteVendorV1AuthenticatedUser
    | undefined;
};

export const VendorsControllerDeleteVendorV1ResponseBody$zodSchema: z.ZodType<
  VendorsControllerDeleteVendorV1ResponseBody
> = z.object({
  authType: VendorsControllerDeleteVendorV1AuthType$zodSchema.optional()
    .describe("How the request was authenticated"),
  authenticatedUser: z.lazy(() =>
    VendorsControllerDeleteVendorV1AuthenticatedUser$zodSchema
  ).optional().describe("User information (only for session auth)"),
  deletedVendor: z.lazy(() => DeletedVendor$zodSchema).optional(),
  message: z.string().optional(),
}).describe("Vendor deleted successfully");

export type VendorsControllerDeleteVendorV1Response =
  | ApiErrorResponseDto
  | VendorsControllerDeleteVendorV1ResponseBody;

export const VendorsControllerDeleteVendorV1Response$zodSchema: z.ZodType<
  VendorsControllerDeleteVendorV1Response
> = z.union([
  ApiErrorResponseDto$zodSchema,
  z.lazy(() => VendorsControllerDeleteVendorV1ResponseBody$zodSchema),
]);
