/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Residual likelihood frozen at acceptance
 */
export const VendorAcceptancesControllerListVendorAcceptancesV1ResidualLikelihood =
  {
    VeryUnlikely: "very_unlikely",
    Unlikely: "unlikely",
    Possible: "possible",
    Likely: "likely",
    VeryLikely: "very_likely",
  } as const;
/**
 * Residual likelihood frozen at acceptance
 */
export type VendorAcceptancesControllerListVendorAcceptancesV1ResidualLikelihood =
  ClosedEnum<
    typeof VendorAcceptancesControllerListVendorAcceptancesV1ResidualLikelihood
  >;

export const VendorAcceptancesControllerListVendorAcceptancesV1ResidualLikelihood$zodSchema =
  z.enum([
    "very_unlikely",
    "unlikely",
    "possible",
    "likely",
    "very_likely",
  ]).describe("Residual likelihood frozen at acceptance");

/**
 * Residual impact frozen at acceptance
 */
export const VendorAcceptancesControllerListVendorAcceptancesV1ResidualImpact =
  {
    Insignificant: "insignificant",
    Minor: "minor",
    Moderate: "moderate",
    Major: "major",
    Severe: "severe",
  } as const;
/**
 * Residual impact frozen at acceptance
 */
export type VendorAcceptancesControllerListVendorAcceptancesV1ResidualImpact =
  ClosedEnum<
    typeof VendorAcceptancesControllerListVendorAcceptancesV1ResidualImpact
  >;

export const VendorAcceptancesControllerListVendorAcceptancesV1ResidualImpact$zodSchema =
  z.enum([
    "insignificant",
    "minor",
    "moderate",
    "major",
    "severe",
  ]).describe("Residual impact frozen at acceptance");

/**
 * Risk level of the accepted residual rating
 */
export const VendorAcceptancesControllerListVendorAcceptancesV1Level = {
  VeryLow: "very-low",
  Low: "low",
  Medium: "medium",
  High: "high",
  VeryHigh: "very-high",
} as const;
/**
 * Risk level of the accepted residual rating
 */
export type VendorAcceptancesControllerListVendorAcceptancesV1Level =
  ClosedEnum<typeof VendorAcceptancesControllerListVendorAcceptancesV1Level>;

export const VendorAcceptancesControllerListVendorAcceptancesV1Level$zodSchema =
  z.enum([
    "very-low",
    "low",
    "medium",
    "high",
    "very-high",
  ]).describe("Risk level of the accepted residual rating");

/**
 * How the request was authenticated
 */
export const VendorAcceptancesControllerListVendorAcceptancesV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
  Service: "service",
} as const;
/**
 * How the request was authenticated
 */
export type VendorAcceptancesControllerListVendorAcceptancesV1AuthType =
  ClosedEnum<typeof VendorAcceptancesControllerListVendorAcceptancesV1AuthType>;

export const VendorAcceptancesControllerListVendorAcceptancesV1AuthType$zodSchema =
  z.enum([
    "api-key",
    "session",
    "service",
  ]).describe("How the request was authenticated");

export type VendorAcceptancesControllerListVendorAcceptancesV1Request = {
  id: string;
};

export const VendorAcceptancesControllerListVendorAcceptancesV1Request$zodSchema:
  z.ZodType<VendorAcceptancesControllerListVendorAcceptancesV1Request> = z
    .object({
      id: z.string().describe("Vendor ID"),
    });

/**
 * Internal server error
 */
export type VendorAcceptancesControllerListVendorAcceptancesV1InternalServerErrorResponseBody =
  { message?: string | undefined };

export const VendorAcceptancesControllerListVendorAcceptancesV1InternalServerErrorResponseBody$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerListVendorAcceptancesV1InternalServerErrorResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Internal server error");

/**
 * Vendor not found
 */
export type VendorAcceptancesControllerListVendorAcceptancesV1NotFoundResponseBody =
  { message?: string | undefined };

export const VendorAcceptancesControllerListVendorAcceptancesV1NotFoundResponseBody$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerListVendorAcceptancesV1NotFoundResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Vendor not found");

/**
 * Forbidden - User does not have permission to access vendor risks
 */
export type VendorAcceptancesControllerListVendorAcceptancesV1ForbiddenResponseBody =
  { message?: string | undefined };

export const VendorAcceptancesControllerListVendorAcceptancesV1ForbiddenResponseBody$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerListVendorAcceptancesV1ForbiddenResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe(
    "Forbidden - User does not have permission to access vendor risks",
  );

/**
 * Unauthorized - Invalid authentication
 */
export type VendorAcceptancesControllerListVendorAcceptancesV1UnauthorizedResponseBody =
  { message?: string | undefined };

export const VendorAcceptancesControllerListVendorAcceptancesV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerListVendorAcceptancesV1UnauthorizedResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Unauthorized - Invalid authentication");

export type VendorAcceptancesControllerListVendorAcceptancesV1Data = {
  id?: string | undefined;
  acceptedById?: string | null | undefined;
  acceptedByName?: string | undefined;
  notes?: string | null | undefined;
  residualLikelihood?:
    | VendorAcceptancesControllerListVendorAcceptancesV1ResidualLikelihood
    | undefined;
  residualImpact?:
    | VendorAcceptancesControllerListVendorAcceptancesV1ResidualImpact
    | undefined;
  level?: VendorAcceptancesControllerListVendorAcceptancesV1Level | undefined;
  levelLabel?: string | undefined;
  stale?: boolean | undefined;
  createdAt?: string | undefined;
};

export const VendorAcceptancesControllerListVendorAcceptancesV1Data$zodSchema:
  z.ZodType<VendorAcceptancesControllerListVendorAcceptancesV1Data> = z.object({
    acceptedById: z.string().nullable().optional().describe(
      "Member ID of the acceptor (null if since removed)",
    ),
    acceptedByName: z.string().optional().describe(
      "Acceptor display name, frozen at acceptance",
    ),
    createdAt: z.iso.datetime({ offset: true }).optional().describe(
      "When the acceptance was recorded (server-set, immutable)",
    ),
    id: z.string().optional().describe("Acceptance event ID"),
    level: VendorAcceptancesControllerListVendorAcceptancesV1Level$zodSchema
      .optional().describe("Risk level of the accepted residual rating"),
    levelLabel: z.string().optional().describe("Human-readable level label"),
    notes: z.string().nullable().optional(),
    residualImpact:
      VendorAcceptancesControllerListVendorAcceptancesV1ResidualImpact$zodSchema
        .optional().describe("Residual impact frozen at acceptance"),
    residualLikelihood:
      VendorAcceptancesControllerListVendorAcceptancesV1ResidualLikelihood$zodSchema
        .optional().describe("Residual likelihood frozen at acceptance"),
    stale: z.boolean().optional().describe(
      "True when the residual rating changed after this acceptance was recorded — re-acceptance is required",
    ),
  });

/**
 * User information (only for session auth)
 */
export type VendorAcceptancesControllerListVendorAcceptancesV1AuthenticatedUser =
  { id?: string | undefined; email?: string | undefined };

export const VendorAcceptancesControllerListVendorAcceptancesV1AuthenticatedUser$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerListVendorAcceptancesV1AuthenticatedUser
  > = z.object({
    email: z.string().optional(),
    id: z.string().optional(),
  }).describe("User information (only for session auth)");

/**
 * Acceptance history retrieved successfully (newest first)
 */
export type VendorAcceptancesControllerListVendorAcceptancesV1ResponseBody = {
  data?:
    | Array<VendorAcceptancesControllerListVendorAcceptancesV1Data>
    | undefined;
  authType?:
    | VendorAcceptancesControllerListVendorAcceptancesV1AuthType
    | undefined;
  authenticatedUser?:
    | VendorAcceptancesControllerListVendorAcceptancesV1AuthenticatedUser
    | undefined;
};

export const VendorAcceptancesControllerListVendorAcceptancesV1ResponseBody$zodSchema:
  z.ZodType<VendorAcceptancesControllerListVendorAcceptancesV1ResponseBody> = z
    .object({
      authType:
        VendorAcceptancesControllerListVendorAcceptancesV1AuthType$zodSchema
          .optional().describe("How the request was authenticated"),
      authenticatedUser: z.lazy(() =>
        VendorAcceptancesControllerListVendorAcceptancesV1AuthenticatedUser$zodSchema
      ).optional().describe("User information (only for session auth)"),
      data: z.array(
        z.lazy(() =>
          VendorAcceptancesControllerListVendorAcceptancesV1Data$zodSchema
        ),
      ).optional(),
    }).describe("Acceptance history retrieved successfully (newest first)");

export type VendorAcceptancesControllerListVendorAcceptancesV1Response =
  | VendorAcceptancesControllerListVendorAcceptancesV1ResponseBody
  | VendorAcceptancesControllerListVendorAcceptancesV1UnauthorizedResponseBody
  | VendorAcceptancesControllerListVendorAcceptancesV1ForbiddenResponseBody
  | VendorAcceptancesControllerListVendorAcceptancesV1NotFoundResponseBody
  | VendorAcceptancesControllerListVendorAcceptancesV1InternalServerErrorResponseBody;

export const VendorAcceptancesControllerListVendorAcceptancesV1Response$zodSchema:
  z.ZodType<VendorAcceptancesControllerListVendorAcceptancesV1Response> = z
    .union([
      z.lazy(() =>
        VendorAcceptancesControllerListVendorAcceptancesV1ResponseBody$zodSchema
      ),
      z.lazy(() =>
        VendorAcceptancesControllerListVendorAcceptancesV1UnauthorizedResponseBody$zodSchema
      ),
      z.lazy(() =>
        VendorAcceptancesControllerListVendorAcceptancesV1ForbiddenResponseBody$zodSchema
      ),
      z.lazy(() =>
        VendorAcceptancesControllerListVendorAcceptancesV1NotFoundResponseBody$zodSchema
      ),
      z.lazy(() =>
        VendorAcceptancesControllerListVendorAcceptancesV1InternalServerErrorResponseBody$zodSchema
      ),
    ]);
