/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  CreateRiskAcceptanceDto,
  CreateRiskAcceptanceDto$zodSchema,
} from "./createriskacceptancedto.js";

/**
 * Residual likelihood frozen at acceptance
 */
export const VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualLikelihood =
  {
    VeryUnlikely: "very_unlikely",
    Unlikely: "unlikely",
    Possible: "possible",
    Likely: "likely",
    VeryLikely: "very_likely",
  } as const;
/**
 * Residual likelihood frozen at acceptance
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualLikelihood =
  ClosedEnum<
    typeof VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualLikelihood
  >;

export const VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualLikelihood$zodSchema =
  z.enum([
    "very_unlikely",
    "unlikely",
    "possible",
    "likely",
    "very_likely",
  ]).describe("Residual likelihood frozen at acceptance");

/**
 * Residual impact frozen at acceptance
 */
export const VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualImpact =
  {
    Insignificant: "insignificant",
    Minor: "minor",
    Moderate: "moderate",
    Major: "major",
    Severe: "severe",
  } as const;
/**
 * Residual impact frozen at acceptance
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualImpact =
  ClosedEnum<
    typeof VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualImpact
  >;

export const VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualImpact$zodSchema =
  z.enum([
    "insignificant",
    "minor",
    "moderate",
    "major",
    "severe",
  ]).describe("Residual impact frozen at acceptance");

/**
 * Risk level of the accepted residual rating
 */
export const VendorAcceptancesControllerRecordVendorAcceptanceV1Level = {
  VeryLow: "very-low",
  Low: "low",
  Medium: "medium",
  High: "high",
  VeryHigh: "very-high",
} as const;
/**
 * Risk level of the accepted residual rating
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1Level =
  ClosedEnum<typeof VendorAcceptancesControllerRecordVendorAcceptanceV1Level>;

export const VendorAcceptancesControllerRecordVendorAcceptanceV1Level$zodSchema =
  z.enum([
    "very-low",
    "low",
    "medium",
    "high",
    "very-high",
  ]).describe("Risk level of the accepted residual rating");

/**
 * How the request was authenticated
 */
export const VendorAcceptancesControllerRecordVendorAcceptanceV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
  Service: "service",
} as const;
/**
 * How the request was authenticated
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1AuthType =
  ClosedEnum<
    typeof VendorAcceptancesControllerRecordVendorAcceptanceV1AuthType
  >;

export const VendorAcceptancesControllerRecordVendorAcceptanceV1AuthType$zodSchema =
  z.enum([
    "api-key",
    "session",
    "service",
  ]).describe("How the request was authenticated");

export type VendorAcceptancesControllerRecordVendorAcceptanceV1Request = {
  id: string;
  body: CreateRiskAcceptanceDto;
};

export const VendorAcceptancesControllerRecordVendorAcceptanceV1Request$zodSchema:
  z.ZodType<VendorAcceptancesControllerRecordVendorAcceptanceV1Request> = z
    .object({
      body: CreateRiskAcceptanceDto$zodSchema.describe(
        "Acceptance data (acceptor defaults to the vendor owner)",
      ),
      id: z.string().describe("Vendor ID"),
    });

/**
 * Internal server error
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1InternalServerErrorResponseBody =
  { message?: string | undefined };

export const VendorAcceptancesControllerRecordVendorAcceptanceV1InternalServerErrorResponseBody$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerRecordVendorAcceptanceV1InternalServerErrorResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Internal server error");

/**
 * Vendor not found
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1NotFoundResponseBody =
  { message?: string | undefined };

export const VendorAcceptancesControllerRecordVendorAcceptanceV1NotFoundResponseBody$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerRecordVendorAcceptanceV1NotFoundResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Vendor not found");

/**
 * Forbidden - User does not have permission to access vendor risks
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1ForbiddenResponseBody =
  { message?: string | undefined };

export const VendorAcceptancesControllerRecordVendorAcceptanceV1ForbiddenResponseBody$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerRecordVendorAcceptanceV1ForbiddenResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe(
    "Forbidden - User does not have permission to access vendor risks",
  );

/**
 * Unauthorized - Invalid authentication
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1UnauthorizedResponseBody =
  { message?: string | undefined };

export const VendorAcceptancesControllerRecordVendorAcceptanceV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerRecordVendorAcceptanceV1UnauthorizedResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Unauthorized - Invalid authentication");

/**
 * No owner assigned, or the acceptor is not a valid member
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1BadRequestResponseBody =
  { message?: string | undefined };

export const VendorAcceptancesControllerRecordVendorAcceptanceV1BadRequestResponseBody$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerRecordVendorAcceptanceV1BadRequestResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("No owner assigned, or the acceptor is not a valid member");

/**
 * User information (only for session auth)
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1AuthenticatedUser =
  { id?: string | undefined; email?: string | undefined };

export const VendorAcceptancesControllerRecordVendorAcceptanceV1AuthenticatedUser$zodSchema:
  z.ZodType<
    VendorAcceptancesControllerRecordVendorAcceptanceV1AuthenticatedUser
  > = z.object({
    email: z.string().optional(),
    id: z.string().optional(),
  }).describe("User information (only for session auth)");

/**
 * Acceptance recorded successfully
 */
export type VendorAcceptancesControllerRecordVendorAcceptanceV1ResponseBody = {
  id?: string | undefined;
  acceptedById?: string | null | undefined;
  acceptedByName?: string | undefined;
  notes?: string | null | undefined;
  residualLikelihood?:
    | VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualLikelihood
    | undefined;
  residualImpact?:
    | VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualImpact
    | undefined;
  level?: VendorAcceptancesControllerRecordVendorAcceptanceV1Level | undefined;
  levelLabel?: string | undefined;
  stale?: boolean | undefined;
  createdAt?: string | undefined;
  authType?:
    | VendorAcceptancesControllerRecordVendorAcceptanceV1AuthType
    | undefined;
  authenticatedUser?:
    | VendorAcceptancesControllerRecordVendorAcceptanceV1AuthenticatedUser
    | undefined;
};

export const VendorAcceptancesControllerRecordVendorAcceptanceV1ResponseBody$zodSchema:
  z.ZodType<VendorAcceptancesControllerRecordVendorAcceptanceV1ResponseBody> = z
    .object({
      acceptedById: z.string().nullable().optional().describe(
        "Member ID of the acceptor (null if since removed)",
      ),
      acceptedByName: z.string().optional().describe(
        "Acceptor display name, frozen at acceptance",
      ),
      authType:
        VendorAcceptancesControllerRecordVendorAcceptanceV1AuthType$zodSchema
          .optional().describe("How the request was authenticated"),
      authenticatedUser: z.lazy(() =>
        VendorAcceptancesControllerRecordVendorAcceptanceV1AuthenticatedUser$zodSchema
      ).optional().describe("User information (only for session auth)"),
      createdAt: z.iso.datetime({ offset: true }).optional().describe(
        "When the acceptance was recorded (server-set, immutable)",
      ),
      id: z.string().optional().describe("Acceptance event ID"),
      level: VendorAcceptancesControllerRecordVendorAcceptanceV1Level$zodSchema
        .optional().describe("Risk level of the accepted residual rating"),
      levelLabel: z.string().optional().describe("Human-readable level label"),
      notes: z.string().nullable().optional(),
      residualImpact:
        VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualImpact$zodSchema
          .optional().describe("Residual impact frozen at acceptance"),
      residualLikelihood:
        VendorAcceptancesControllerRecordVendorAcceptanceV1ResidualLikelihood$zodSchema
          .optional().describe("Residual likelihood frozen at acceptance"),
      stale: z.boolean().optional().describe(
        "True when the residual rating changed after this acceptance was recorded — re-acceptance is required",
      ),
    }).describe("Acceptance recorded successfully");

export type VendorAcceptancesControllerRecordVendorAcceptanceV1Response =
  | VendorAcceptancesControllerRecordVendorAcceptanceV1ResponseBody
  | VendorAcceptancesControllerRecordVendorAcceptanceV1BadRequestResponseBody
  | VendorAcceptancesControllerRecordVendorAcceptanceV1UnauthorizedResponseBody
  | VendorAcceptancesControllerRecordVendorAcceptanceV1ForbiddenResponseBody
  | VendorAcceptancesControllerRecordVendorAcceptanceV1NotFoundResponseBody
  | VendorAcceptancesControllerRecordVendorAcceptanceV1InternalServerErrorResponseBody;

export const VendorAcceptancesControllerRecordVendorAcceptanceV1Response$zodSchema:
  z.ZodType<VendorAcceptancesControllerRecordVendorAcceptanceV1Response> = z
    .union([
      z.lazy(() =>
        VendorAcceptancesControllerRecordVendorAcceptanceV1ResponseBody$zodSchema
      ),
      z.lazy(() =>
        VendorAcceptancesControllerRecordVendorAcceptanceV1BadRequestResponseBody$zodSchema
      ),
      z.lazy(() =>
        VendorAcceptancesControllerRecordVendorAcceptanceV1UnauthorizedResponseBody$zodSchema
      ),
      z.lazy(() =>
        VendorAcceptancesControllerRecordVendorAcceptanceV1ForbiddenResponseBody$zodSchema
      ),
      z.lazy(() =>
        VendorAcceptancesControllerRecordVendorAcceptanceV1NotFoundResponseBody$zodSchema
      ),
      z.lazy(() =>
        VendorAcceptancesControllerRecordVendorAcceptanceV1InternalServerErrorResponseBody$zodSchema
      ),
    ]);
