/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { controlsControlsControllerFindOneV1 } from "../../funcs/controlsControlsControllerFindOneV1.js";
import { ControlsControllerFindOneV1Request$zodSchema } from "../../models/controlscontrollerfindonev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ControlsControllerFindOneV1Request$zodSchema,
};

export const tool$controlsControlsControllerFindOneV1: ToolDefinition<
  typeof args
> = {
  name: "controls-find-one",
  description: `Get control detail with progress

Get control detail with progress in OpenComp. Manage controls, map them to policies, tasks, framework requirements, and evidence document types, and track implementation progress.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await controlsControlsControllerFindOneV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
