/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { controlsControlsControllerLinkPoliciesV1 } from "../../funcs/controlsControlsControllerLinkPoliciesV1.js";
import { ControlsControllerLinkPoliciesV1Request$zodSchema } from "../../models/controlscontrollerlinkpoliciesv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ControlsControllerLinkPoliciesV1Request$zodSchema,
};

export const tool$controlsControlsControllerLinkPoliciesV1: ToolDefinition<
  typeof args
> = {
  name: "link-policies",
  description: `Link policies to control

Link policies to a control so auditors and reviewers can trace control implementation back to approved policy evidence.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await controlsControlsControllerLinkPoliciesV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
