/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { controlsControlsControllerCreateV1 } from "../../funcs/controlsControlsControllerCreateV1.js";
import { CreateControlDto$zodSchema } from "../../models/createcontroldto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateControlDto$zodSchema,
};

export const tool$controlsControlsControllerCreateV1: ToolDefinition<
  typeof args
> = {
  name: "create",
  description: `Create compliance control

Create a custom compliance control and connect it to framework requirements, policies, tasks, and evidence expectations.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await controlsControlsControllerCreateV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
