/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { controlsControlsControllerGetOptionsV1 } from "../../funcs/controlsControlsControllerGetOptionsV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$controlsControlsControllerGetOptionsV1: ToolDefinition = {
  name: "get-options",
  description: `Get dropdown options for creating controls

Get dropdown options for creating controls in OpenComp. Manage controls, map them to policies, tasks, framework requirements, and evidence document types, and track implementation progress.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result] = await controlsControlsControllerGetOptionsV1(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
