/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { controlsControlsControllerFindAllV1 } from "../../funcs/controlsControlsControllerFindAllV1.js";
import { ControlsControllerFindAllV1Request$zodSchema } from "../../models/controlscontrollerfindallv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ControlsControllerFindAllV1Request$zodSchema.optional(),
};

export const tool$controlsControlsControllerFindAllV1: ToolDefinition<
  typeof args
> = {
  name: "controls-find-all",
  description: `List compliance controls

List controls with linked policies, tasks, requirements, and document types for SOC 2, ISO 27001, HIPAA, and GDPR programs.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await controlsControlsControllerFindAllV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
