/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { controlsControlsControllerLinkRequirementsV1 } from "../../funcs/controlsControlsControllerLinkRequirementsV1.js";
import { ControlsControllerLinkRequirementsV1Request$zodSchema } from "../../models/controlscontrollerlinkrequirementsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ControlsControllerLinkRequirementsV1Request$zodSchema,
};

export const tool$controlsControlsControllerLinkRequirementsV1: ToolDefinition<
  typeof args
> = {
  name: "controls-link-requirements",
  description: `Link existing requirements to a control

Link existing requirements to a control in OpenComp. Manage controls, map them to policies, tasks, framework requirements, and evidence document types, and track implementation progress.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await controlsControlsControllerLinkRequirementsV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
