/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { controlsControlsControllerUnlinkDocumentTypeV1 } from "../../funcs/controlsControlsControllerUnlinkDocumentTypeV1.js";
import { ControlsControllerUnlinkDocumentTypeV1Request$zodSchema } from "../../models/controlscontrollerunlinkdocumenttypev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ControlsControllerUnlinkDocumentTypeV1Request$zodSchema,
};

export const tool$controlsControlsControllerUnlinkDocumentTypeV1:
  ToolDefinition<typeof args> = {
    name: "unlink-document-type",
    description: `Remove a required document type from a control

Remove a required document type from a control in OpenComp. Manage controls, map them to policies, tasks, framework requirements, and evidence document types, and track implementation progress.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await controlsControlsControllerUnlinkDocumentTypeV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
