/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { controlsControlsControllerLinkTasksV1 } from "../../funcs/controlsControlsControllerLinkTasksV1.js";
import { ControlsControllerLinkTasksV1Request$zodSchema } from "../../models/controlscontrollerlinktasksv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ControlsControllerLinkTasksV1Request$zodSchema,
};

export const tool$controlsControlsControllerLinkTasksV1: ToolDefinition<
  typeof args
> = {
  name: "link-tasks",
  description: `Link tasks to control

Link compliance tasks to a control so implementation work, evidence collection, and review status stay connected.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await controlsControlsControllerLinkTasksV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
