/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerFindAvailableV1 } from "../../funcs/frameworksFrameworksControllerFindAvailableV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$frameworksFrameworksControllerFindAvailableV1:
  ToolDefinition = {
    name: "find-available",
    description: `List available frameworks

List frameworks available for activation before starting a new compliance program or expanding into another standard.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    tool: async (client, ctx) => {
      const [result] = await frameworksFrameworksControllerFindAvailableV1(
        client,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
