/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerGetSyncHistoryV1 } from "../../funcs/frameworksFrameworksControllerGetSyncHistoryV1.js";
import { FrameworksControllerGetSyncHistoryV1Request$zodSchema } from "../../models/frameworkscontrollergetsynchistoryv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerGetSyncHistoryV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerGetSyncHistoryV1:
  ToolDefinition<typeof args> = {
    name: "get-sync-history",
    description: `Get sync history for a framework instance

Get sync history for a framework instance in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await frameworksFrameworksControllerGetSyncHistoryV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
