/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerRollbackFrameworkV1 } from "../../funcs/frameworksFrameworksControllerRollbackFrameworkV1.js";
import { FrameworksControllerRollbackFrameworkV1Request$zodSchema } from "../../models/frameworkscontrollerrollbackframeworkv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerRollbackFrameworkV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerRollbackFrameworkV1:
  ToolDefinition<typeof args> = {
    name: "rollback-framework",
    description: `Roll back a framework sync operation

Roll back a framework sync operation in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await frameworksFrameworksControllerRollbackFrameworkV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
