/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerDeleteV1 } from "../../funcs/frameworksFrameworksControllerDeleteV1.js";
import { FrameworksControllerDeleteV1Request$zodSchema } from "../../models/frameworkscontrollerdeletev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerDeleteV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerDeleteV1: ToolDefinition<
  typeof args
> = {
  name: "delete",
  description: `Delete a framework instance

Delete a framework instance in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await frameworksFrameworksControllerDeleteV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
