/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerFindRequirementV1 } from "../../funcs/frameworksFrameworksControllerFindRequirementV1.js";
import { FrameworksControllerFindRequirementV1Request$zodSchema } from "../../models/frameworkscontrollerfindrequirementv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerFindRequirementV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerFindRequirementV1:
  ToolDefinition<typeof args> = {
    name: "find-requirement",
    description: `Get a specific requirement with related controls

Get a specific requirement with related controls in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await frameworksFrameworksControllerFindRequirementV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
