/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerAddFrameworksV1 } from "../../funcs/frameworksFrameworksControllerAddFrameworksV1.js";
import { AddFrameworksDto$zodSchema } from "../../models/addframeworksdto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AddFrameworksDto$zodSchema,
};

export const tool$frameworksFrameworksControllerAddFrameworksV1: ToolDefinition<
  typeof args
> = {
  name: "add-frameworks",
  description: `Add compliance frameworks

Add one or more compliance frameworks to an organization so tasks, controls, evidence, and readiness tracking can be generated.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await frameworksFrameworksControllerAddFrameworksV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
