/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerSyncFrameworkV1 } from "../../funcs/frameworksFrameworksControllerSyncFrameworkV1.js";
import { FrameworksControllerSyncFrameworkV1Request$zodSchema } from "../../models/frameworkscontrollersyncframeworkv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerSyncFrameworkV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerSyncFrameworkV1: ToolDefinition<
  typeof args
> = {
  name: "sync-framework",
  description: `Sync framework requirements

Sync framework requirements, controls, and tasks after framework content changes so compliance tracking remains current.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await frameworksFrameworksControllerSyncFrameworkV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
