/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerFindOneV1 } from "../../funcs/frameworksFrameworksControllerFindOneV1.js";
import { FrameworksControllerFindOneV1Request$zodSchema } from "../../models/frameworkscontrollerfindonev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerFindOneV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerFindOneV1: ToolDefinition<
  typeof args
> = {
  name: "frameworks-find-one",
  description: `Get a single framework instance with full detail

Get a single framework instance with full detail in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await frameworksFrameworksControllerFindOneV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
