/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerFindAllV1 } from "../../funcs/frameworksFrameworksControllerFindAllV1.js";
import { FrameworksControllerFindAllV1Request$zodSchema } from "../../models/frameworkscontrollerfindallv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerFindAllV1Request$zodSchema.optional(),
};

export const tool$frameworksFrameworksControllerFindAllV1: ToolDefinition<
  typeof args
> = {
  name: "frameworks-find-all",
  description: `List compliance frameworks

List active SOC 2, ISO 27001, HIPAA, GDPR, and custom compliance frameworks with implementation status and progress data.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await frameworksFrameworksControllerFindAllV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
