/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerCreateRequirementV1 } from "../../funcs/frameworksFrameworksControllerCreateRequirementV1.js";
import { FrameworksControllerCreateRequirementV1Request$zodSchema } from "../../models/frameworkscontrollercreaterequirementv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerCreateRequirementV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerCreateRequirementV1:
  ToolDefinition<typeof args> = {
    name: "create-requirement",
    description: `Add a custom requirement to a framework instance

Add a custom requirement to a framework instance in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await frameworksFrameworksControllerCreateRequirementV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
