/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerGetAllUpdateStatusesV1 } from "../../funcs/frameworksFrameworksControllerGetAllUpdateStatusesV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$frameworksFrameworksControllerGetAllUpdateStatusesV1:
  ToolDefinition = {
    name: "get-all-update-statuses",
    description: `Get update statuses for all framework instances

Get update statuses for all framework instances in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    tool: async (client, ctx) => {
      const [result] =
        await frameworksFrameworksControllerGetAllUpdateStatusesV1(
          client,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
