/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerLinkRequirementsV1 } from "../../funcs/frameworksFrameworksControllerLinkRequirementsV1.js";
import { FrameworksControllerLinkRequirementsV1Request$zodSchema } from "../../models/frameworkscontrollerlinkrequirementsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerLinkRequirementsV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerLinkRequirementsV1:
  ToolDefinition<typeof args> = {
    name: "link-requirements",
    description:
      `Link (clone) existing requirements from another framework into this one

Link (clone) existing requirements from another framework into this one in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await frameworksFrameworksControllerLinkRequirementsV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
