/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerUpdateCustomV1 } from "../../funcs/frameworksFrameworksControllerUpdateCustomV1.js";
import { FrameworksControllerUpdateCustomV1Request$zodSchema } from "../../models/frameworkscontrollerupdatecustomv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerUpdateCustomV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerUpdateCustomV1: ToolDefinition<
  typeof args
> = {
  name: "update-custom",
  description: `Update a custom framework

Update the name and/or description of an organization's custom framework. Only custom frameworks are editable; platform frameworks return 400.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await frameworksFrameworksControllerUpdateCustomV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
