/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerCreateCustomV1 } from "../../funcs/frameworksFrameworksControllerCreateCustomV1.js";
import { CreateCustomFrameworkDto$zodSchema } from "../../models/createcustomframeworkdto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateCustomFrameworkDto$zodSchema,
};

export const tool$frameworksFrameworksControllerCreateCustomV1: ToolDefinition<
  typeof args
> = {
  name: "create-custom",
  description: `Create a custom framework for this organization

Create a custom framework for this organization in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await frameworksFrameworksControllerCreateCustomV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
