/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerGetUpdatePreviewV1 } from "../../funcs/frameworksFrameworksControllerGetUpdatePreviewV1.js";
import { FrameworksControllerGetUpdatePreviewV1Request$zodSchema } from "../../models/frameworkscontrollergetupdatepreviewv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerGetUpdatePreviewV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerGetUpdatePreviewV1:
  ToolDefinition<typeof args> = {
    name: "get-update-preview",
    description: `Preview changes from updating a framework instance

Preview changes from updating a framework instance in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await frameworksFrameworksControllerGetUpdatePreviewV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
