/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerLinkControlsV1 } from "../../funcs/frameworksFrameworksControllerLinkControlsV1.js";
import { FrameworksControllerLinkControlsV1Request$zodSchema } from "../../models/frameworkscontrollerlinkcontrolsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FrameworksControllerLinkControlsV1Request$zodSchema,
};

export const tool$frameworksFrameworksControllerLinkControlsV1: ToolDefinition<
  typeof args
> = {
  name: "link-controls",
  description: `Link existing org controls to a requirement

Link existing org controls to a requirement in OpenComp. Manage SOC 2, ISO 27001, HIPAA, GDPR, and custom framework instances, requirements, scores, and sync history.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await frameworksFrameworksControllerLinkControlsV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
