/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { frameworksFrameworksControllerGetScoresV1 } from "../../funcs/frameworksFrameworksControllerGetScoresV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$frameworksFrameworksControllerGetScoresV1: ToolDefinition = {
  name: "get-scores",
  description: `Get framework readiness scores

Retrieve framework readiness scores so teams can report progress toward audit readiness across active compliance standards.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result] = await frameworksFrameworksControllerGetScoresV1(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
