/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ismsISMSProfileControllerSaveProfileV1 } from "../../funcs/ismsISMSProfileControllerSaveProfileV1.js";
import { IsmsProfileControllerSaveProfileV1Request$zodSchema } from "../../models/ismsprofilecontrollersaveprofilev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: IsmsProfileControllerSaveProfileV1Request$zodSchema.describe(
    `Partial ISMS wizard answers (validated at runtime by zod)`,
  ),
};

export const tool$ismsISMSProfileControllerSaveProfileV1: ToolDefinition<
  typeof args
> = {
  name: "save-profile",
  description: `Save (partial) ISMS wizard answers

Save (partial) ISMS wizard answers in OpenComp. Create and manage ISO 27001 ISMS documents, control mappings, register rows, and narratives, and run wizard-based setup, approval, and drift review workflows.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await ismsISMSProfileControllerSaveProfileV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
