/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ismsISMSControllerGenerateV1 } from "../../funcs/ismsISMSControllerGenerateV1.js";
import { IsmsControllerGenerateV1Request$zodSchema } from "../../models/ismscontrollergeneratev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: IsmsControllerGenerateV1Request$zodSchema,
};

export const tool$ismsISMSControllerGenerateV1: ToolDefinition<typeof args> = {
  name: "generate",
  description: `Derive Context-of-the-Organization issues

Derive Context-of-the-Organization issues in OpenComp. Create and manage ISO 27001 ISMS documents, control mappings, register rows, and narratives, and run wizard-based setup, approval, and drift review workflows.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await ismsISMSControllerGenerateV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
