/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ismsISMSRegistersControllerCreateRowV1 } from "../../funcs/ismsISMSRegistersControllerCreateRowV1.js";
import { IsmsRegistersControllerCreateRowV1Request$zodSchema } from "../../models/ismsregisterscontrollercreaterowv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: IsmsRegistersControllerCreateRowV1Request$zodSchema,
};

export const tool$ismsISMSRegistersControllerCreateRowV1: ToolDefinition<
  typeof args
> = {
  name: "create-row",
  description: `Create a row in an ISMS register

Create a row in an ISMS register in OpenComp. Create and manage ISO 27001 ISMS documents, control mappings, register rows, and narratives, and run wizard-based setup, approval, and drift review workflows.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await ismsISMSRegistersControllerCreateRowV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
