/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ismsISMSControllerRiskTreatmentV1 } from "../../funcs/ismsISMSControllerRiskTreatmentV1.js";
import { IsmsControllerRiskTreatmentV1Request$zodSchema } from "../../models/ismscontrollerrisktreatmentv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: IsmsControllerRiskTreatmentV1Request$zodSchema,
};

export const tool$ismsISMSControllerRiskTreatmentV1: ToolDefinition<
  typeof args
> = {
  name: "risk-treatment",
  description: `The Risk Treatment Plan's rows (Clause 6.1.3)

Returns the organisational and supplier risk rows the Risk Treatment Plan renders (from the Risk Register and Vendors, with acceptance state per row) plus its submit-readiness messages.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await ismsISMSControllerRiskTreatmentV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
