/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ismsISMSControllerSubmitForApprovalV1 } from "../../funcs/ismsISMSControllerSubmitForApprovalV1.js";
import { IsmsControllerSubmitForApprovalV1Request$zodSchema } from "../../models/ismscontrollersubmitforapprovalv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: IsmsControllerSubmitForApprovalV1Request$zodSchema,
};

export const tool$ismsISMSControllerSubmitForApprovalV1: ToolDefinition<
  typeof args
> = {
  name: "isms-submit-for-approval",
  description: `Submit an ISMS document for approval

Submit an ISMS document for approval in OpenComp. Create and manage ISO 27001 ISMS documents, control mappings, register rows, and narratives, and run wizard-based setup, approval, and drift review workflows.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await ismsISMSControllerSubmitForApprovalV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
