/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { risksRiskAcceptancesControllerListRiskAcceptancesV1 } from "../../funcs/risksRiskAcceptancesControllerListRiskAcceptancesV1.js";
import { RiskAcceptancesControllerListRiskAcceptancesV1Request$zodSchema } from "../../models/riskacceptancescontrollerlistriskacceptancesv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RiskAcceptancesControllerListRiskAcceptancesV1Request$zodSchema,
};

export const tool$risksRiskAcceptancesControllerListRiskAcceptancesV1:
  ToolDefinition<typeof args> = {
    name: "list-risk-acceptances",
    description: `List risk-owner acceptance events

Returns the residual-risk acceptance history for a risk, newest first. Each event freezes the residual rating at acceptance and carries a stale flag set when the risk's residual rating has changed since (ISO 27001 6.1.3(f)).`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await risksRiskAcceptancesControllerListRiskAcceptancesV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
