/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { risksRiskAcceptancesControllerRecordRiskAcceptanceV1 } from "../../funcs/risksRiskAcceptancesControllerRecordRiskAcceptanceV1.js";
import { RiskAcceptancesControllerRecordRiskAcceptanceV1Request$zodSchema } from "../../models/riskacceptancescontrollerrecordriskacceptancev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RiskAcceptancesControllerRecordRiskAcceptanceV1Request$zodSchema,
};

export const tool$risksRiskAcceptancesControllerRecordRiskAcceptanceV1:
  ToolDefinition<typeof args> = {
    name: "record-risk-acceptance",
    description: `Record risk-owner acceptance

Records an immutable, timestamped acceptance of a risk's current residual risk by the risk owner (or a chosen member). Re-record after the residual rating changes; prior events remain in the history.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await risksRiskAcceptancesControllerRecordRiskAcceptanceV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
