/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { timelinesTimelinesControllerMarkReadyForReviewV1 } from "../../funcs/timelinesTimelinesControllerMarkReadyForReviewV1.js";
import { TimelinesControllerMarkReadyForReviewV1Request$zodSchema } from "../../models/timelinescontrollermarkreadyforreviewv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TimelinesControllerMarkReadyForReviewV1Request$zodSchema,
};

export const tool$timelinesTimelinesControllerMarkReadyForReviewV1:
  ToolDefinition<typeof args> = {
    name: "mark-ready-for-review",
    description: `Mark a phase as ready for review

Mark a phase as ready for review in OpenComp. Track audit and compliance readiness timelines, phases, and review milestones for an organization.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await timelinesTimelinesControllerMarkReadyForReviewV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
