/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { timelinesTimelinesControllerFindOneV1 } from "../../funcs/timelinesTimelinesControllerFindOneV1.js";
import { TimelinesControllerFindOneV1Request$zodSchema } from "../../models/timelinescontrollerfindonev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TimelinesControllerFindOneV1Request$zodSchema,
};

export const tool$timelinesTimelinesControllerFindOneV1: ToolDefinition<
  typeof args
> = {
  name: "find-one",
  description: `Get a single timeline instance with phases

Get a single timeline instance with phases in OpenComp. Track audit and compliance readiness timelines, phases, and review milestones for an organization.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await timelinesTimelinesControllerFindOneV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
