/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { timelinesTimelinesControllerFindAllV1 } from "../../funcs/timelinesTimelinesControllerFindAllV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$timelinesTimelinesControllerFindAllV1: ToolDefinition = {
  name: "find-all",
  description: `List timelines for the organization

List timelines for the organization in OpenComp. Track audit and compliance readiness timelines, phases, and review milestones for an organization.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result] = await timelinesTimelinesControllerFindAllV1(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
