/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trainingTrainingControllerSendHipaaTrainingCompletionEmailV1 } from "../../funcs/trainingTrainingControllerSendHipaaTrainingCompletionEmailV1.js";
import { SendTrainingCompletionDto$zodSchema } from "../../models/sendtrainingcompletiondto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SendTrainingCompletionDto$zodSchema,
};

export const tool$trainingTrainingControllerSendHipaaTrainingCompletionEmailV1:
  ToolDefinition<typeof args> = {
    name: "send-hipaa-training-completion-email",
    description: `Send HIPAA training completion email with certificate

Checks if the member has completed the HIPAA Security Awareness Training. If so, sends an email with the HIPAA training certificate attached.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await trainingTrainingControllerSendHipaaTrainingCompletionEmailV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
