/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustAccessTrustAccessControllerGetPublicProfileV1 } from "../../funcs/trustAccessTrustAccessControllerGetPublicProfileV1.js";
import { TrustAccessControllerGetPublicProfileV1Request$zodSchema } from "../../models/trustaccesscontrollergetpublicprofilev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TrustAccessControllerGetPublicProfileV1Request$zodSchema,
};

export const tool$trustAccessTrustAccessControllerGetPublicProfileV1:
  ToolDefinition<typeof args> = {
    name: "get-public-profile",
    description: `Get public trust portal header data

Get public trust portal header data in OpenComp. Manage external Trust Center access requests, NDA signing, grants, tokenized document downloads, public FAQs, and reviewer access.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await trustAccessTrustAccessControllerGetPublicProfileV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
