/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustAccessTrustAccessControllerGetPublicControlsV1 } from "../../funcs/trustAccessTrustAccessControllerGetPublicControlsV1.js";
import { TrustAccessControllerGetPublicControlsV1Request$zodSchema } from "../../models/trustaccesscontrollergetpubliccontrolsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TrustAccessControllerGetPublicControlsV1Request$zodSchema,
};

export const tool$trustAccessTrustAccessControllerGetPublicControlsV1:
  ToolDefinition<typeof args> = {
    name: "get-public-controls",
    description: `Get control names for a trust portal

Get control names for a trust portal in OpenComp. Manage external Trust Center access requests, NDA signing, grants, tokenized document downloads, public FAQs, and reviewer access.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await trustAccessTrustAccessControllerGetPublicControlsV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
