/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustAccessTrustAccessControllerGetPublicFrameworksV1 } from "../../funcs/trustAccessTrustAccessControllerGetPublicFrameworksV1.js";
import { TrustAccessControllerGetPublicFrameworksV1Request$zodSchema } from "../../models/trustaccesscontrollergetpublicframeworksv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TrustAccessControllerGetPublicFrameworksV1Request$zodSchema,
};

export const tool$trustAccessTrustAccessControllerGetPublicFrameworksV1:
  ToolDefinition<typeof args> = {
    name: "get-public-frameworks",
    description: `Get enabled compliance frameworks for a trust portal

Lists the native frameworks an org displays as compliant, with status and certificate presence. Powers the public compliance rail.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await trustAccessTrustAccessControllerGetPublicFrameworksV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
